import { zhCN } from "./zh-CN";
import type { LocaleCatalog } from "./schema";

const identityDemoText = Object.fromEntries(
  Object.keys(zhCN.demoText).map((key) => [key, key])
) as LocaleCatalog["demoText"];

export const enUS = {
  locale: "en-US",
  app: {
    documentTitle: "StoryGraph Workbench",
    brandName: "StoryGraph Agent",
    tagline: "Safe long-form fiction workbench"
  },
  terms: {
    agent: "Agent",
    api: "API",
    candidateFact: "Candidate fact",
    canon: "Canon",
    canonReview: "Canon review",
    canonSeed: "Canon seed",
    contextPack: "Context pack",
    draftStore: "Draft store",
    factDraft: "Fact draft",
    fastApi: "FastAPI backend",
    graphStore: "Canon graph",
    githubRelease: "GitHub Release",
    llm: "Language model",
    proposalStore: "Proposal store",
    reviewService: "Review service",
    styleSampleStore: "Style sample store",
    tauri: "Tauri desktop app"
  },
  contentDefaults: {
    genre: "fantasy",
    narrativePov: "third-person limited",
    untitledProposal: "Untitled proposal",
    proposalSuffix: "proposal"
  },
  ui: {
    common: {
      all: "All",
      cancel: "Cancel",
      checking: "Checking…",
      create: "Create",
      missing: "Missing",
      none: "None",
      loading: "Loading",
      newItem: "New",
      notConfigured: "Not configured",
      refresh: "Refresh",
      save: "Save",
      undo: "Undo",
      redo: "Redo",
      writing: "Write",
      notCreated: "Not created",
      notSet: "Not set"
    },
    language: {
      uiLocaleLabel: "Interface language",
      chinese: "Simplified Chinese",
      english: "English",
      projectLanguageLabel: "Story language",
      projectLanguageHelp: "Controls new project content and Agent output only. Changing the interface never edits your story.",
      projectLanguageNeedsReview: "The previous language value requires author confirmation",
      projectLanguageChangeConfirm: "Use the new language for future generations only? Existing drafts, proposals, sources, and canon will not be translated or changed.",
      sourceLanguageLabel: "Source language",
      artifactLanguageLabel: "Content language snapshot",
      historicalLanguageUnknown: "Language not recorded historically",
      inferredLanguage: " (legacy inference)",
      detectedChinese: "Detected Chinese",
      detectedEnglish: "Detected English",
      detectedUnknown: "Language undetermined",
      undetermined: "Undetermined (unavailable to Agent)",
      editSourceLanguage: "Correct language",
      saveSourceLanguage: "Save language",
      projectOnly: "Same-language sources only",
      explicitReference: "Explicitly reference other-language sources",
      explicitReferenceHelp: "Only explicitly checked sources are used as references. Nothing is translated automatically, and output stays in the story language.",
      sourceMismatchDisabled: "This source uses a different language. Enable explicit other-language references before selecting it.",
      sourceUnknownDisabled: "Sources with undetermined language cannot be used by the Agent or structure analysis. Correct the language in source details first."
    },
    commandBar: {
      ariaLabel: "Global commands",
      saveDraftTitle: "Save the current scene draft",
      undoTitle: "Undo in the active field",
      redoTitle: "Redo in the active field",
      refreshTitle: "Refresh the backend project tree",
      sourcesTitle: "Open this project's persistent source library",
      agentTitle: "Open Agent discussion",
      proposalsTitle: "Open the proposal workspace",
      runTitle: "Run the scene workflow from the current canon and context"
    },
    tabs: {
      write: "Write",
      sources: "Sources",
      agent: "Agent",
      proposals: "Proposals",
      workflow: "Workflow",
      context: "Context",
      continuity: "Continuity",
      facts: "Facts",
      settings: "Settings"
    },
    stateStrip: {
      projectPrefix: "Project",
      writerPrefix: "Writer",
      llmIncomplete: "Model setup incomplete",
      safetyBoundary: "Drafts, candidate facts, and canon stay separate"
    },
    workspace: {
      emptyTitle: "No project exists on this backend",
      emptyText: "Create a fiction project, then import a manuscript and let the Agent propose a chapter and scene structure.",
      importedStructureTitle: "Build a project structure from a manuscript",
      emptyWorkspaceTitle: "Empty workspace",
      noSceneWithWorkspace: "Import a manuscript under Sources and ask the Agent for a chapter/scene proposal. Nothing enters the project tree until you accept it.",
      noSceneEmptyWorkspace: "Create a project, then import a manuscript to propose its chapter and scene structure.",
      sceneMetadataAria: "Scene metadata",
      mainWorkspaceAria: "Main workspace",
      workflowStatusAria: "Current workflow status"
    },
    library: {
      ariaLabel: "Project source library",
      title: "Project sources / Import",
      summary: (count: number) => `${count} project sources · persisted by the backend · non-canon`,
      fileButton: "Import files",
      folderButton: "Import folder",
      refreshButton: "Refresh sources",
      emptyTitle: "This project has no sources yet",
      emptyText: "Import TXT, Markdown, or DOCX files with their folder structure. They remain available after restart.",
      readerEmptyTitle: "Select a project source",
      readerEmptyText: "The list loads summaries only. Full text is loaded only after selection. Reading or importing never writes drafts, proposals, candidate facts, or canon automatically.",
      readerLoadingTitle: "Loading source text",
      readerLoadingText: "Full text is loaded only when you explicitly open this source.",
      readerLoadFailedTitle: "Source text is not loaded",
      readerLoadFailedText: "Select the source again or refresh the source list.",
      bridgeText: "Every action below is explicit. Only its button can copy loaded text into a draft, proposal, style sample, or structure proposal. Canon is never changed directly.",
      buildStructure: "Propose project structure",
      buildStructureTitle: "Create an editable project structure proposal from the imported manuscript. Chapters and scenes are created only after author approval.",
      saveDraft: "Use as current draft",
      saveDraftTitle: "Save this text as a draft for the current scene without changing canon.",
      saveProposal: "Save to proposals",
      saveProposalTitle: "Save this text to the proposal workspace without changing the current scene draft.",
      saveStyle: "Save as style sample",
      saveStyleTitle: "Save this text as a soft-priority style sample.",
      retry: "Retry extraction",
      retryTitle: "Choose the original file again. Matching path and checksum reuse its stable source ID and retry a failed record.",
      archive: "Archive source",
      archiveTitle: "Hide this source from the normal project list without deleting it. Existing source references remain valid.",
      archiveConfirm: (title: string) => `Archive “${title}”? It will leave the regular list but will not be deleted.`,
      readErrorTitle: "Text extraction failed for this source.",
      unknownReadError: "The backend did not return a specific error. Import the original file again.",
      sourceWarningTitle: "Extraction finished with technical warnings.",
      localRoot: "Project sources",
      importProgress: (current: number, total: number) => `Importing in order ${current} / ${total}`,
      importComplete: "Import complete",
      importCreated: (count: number) => `Created ${count}`,
      importUpdated: (count: number) => `Updated ${count}`,
      importUnchanged: (count: number) => `Unchanged ${count}`,
      importFailed: (count: number) => `Failed ${count}`,
      importSkipped: (count: number) => `Skipped ${count}`,
      importProvenanceNote: "Imported by the author from the project source page.",
      redactedLocalPath: "[local path hidden]",
      importedDraftSummaryPrefix: "Explicitly copied from project source: ",
      importedStyleSummaryPrefix: "Style sample explicitly copied from project source: ",
      importedProposalTitlePrefix: "Imported source proposal: ",
      importedProposalNotePrefix: "Explicitly created by the author from project source: ",
      formats: { txt: "TXT", markdown: "Markdown", docx: "DOCX" }
    },
    proposals: {
      ariaLabel: "Proposal workspace",
      title: "Proposal workspace",
      countSuffix: "items / proposal store",
      filterAria: "Filter proposals by status",
      emptyTitle: "No proposals yet",
      emptyText: "Create one from a project source, Agent workflow, or manual edit.",
      typeAria: "Proposal type",
      titleAria: "Proposal title",
      titlePlaceholder: "Title",
      bodyAria: "Proposal body",
      save: "Save proposal",
      requestAgent: "Ask Agent to revise",
      extractFactDraft: "Create fact draft",
      submitReview: "Submit for review",
      accept: "Accept",
      reject: "Reject",
      promoteDraft: "Promote to scene draft",
      applyStructure: "Apply chapters/scenes",
      sourceDraft: "Source draft",
      sourceDraftPlaceholder: "Source draft ID",
      extractCandidates: "Submit candidate facts",
      openCanonReview: "Open canon review",
      refsSource: "Sources",
      refsTarget: "Targets",
      refsDerived: "Derived",
      metadataStatus: "Status",
      metadataType: "Type",
      metadataVersion: "Version",
      metadataCreatedVia: "Created via",
      unselected: "Not selected",
      newVersion: "New"
    },
    sidebar: {
      workspaceTitle: "Workspace",
      projectTreeAria: "Backend project tree",
      projectEmpty: "The backend has no projects.",
      projectLoading: "Loading backend projects…",
      uncategorized: "Uncategorized",
      languageUnset: "Language not set",
      povUnset: "POV not set",
      chapterCount: "chapters",
      sceneCount: "scenes",
      refreshTitle: "Refresh the project tree from the backend",
      createProject: "New project",
      createProjectTitle: "Create a fiction project",
      editProject: "Edit project",
      editProjectTitle: "Edit the current project",
      archiveDemo: "Remove demo",
      archiveDemoTitle: "Remove only the bundled demo project; real projects are unaffected",
      requireFullPermission: "Full permission required",
      noChapterScenes: "This chapter has no scenes.",
      noProjectTreeTitle: "No backend project tree",
      noProjectTreeText: "After project creation, chapters and scenes are loaded from the canon graph.",
      editProjectTitleText: "Edit project details",
      createProjectTitleText: "Create a fiction project",
      projectNamePlaceholder: "Project name",
      genrePlaceholder: "Genre",
      languagePlaceholder: "Language",
      targetLengthPlaceholder: "Target length",
      narrativePovPlaceholder: "Narrative POV",
      saveProjectInfo: "Save details",
      createProjectButton: "Create project",
      outlineTitle: "Chapters / Scenes",
      chapterTitlePlaceholder: "Chapter title",
      volumeIndexPlaceholder: "Volume number",
      chapterIndexPlaceholder: "Chapter number",
      chapterStatusAria: "Chapter status",
      addChapter: "Add chapter",
      chapterPurposePlaceholder: "Chapter purpose",
      chapterSummaryPlaceholder: "Chapter summary",
      loadChapter: "Load chapter",
      loadChapterTitle: "Load the selected chapter into the form above",
      saveChapterMetadata: "Save chapter metadata",
      saveChapterMetadataTitle: "Save metadata for the selected chapter",
      chooseChapter: "Choose chapter",
      sceneTitlePlaceholder: "Scene title",
      sceneIndexPlaceholder: "Scene number",
      addScene: "Add scene",
      loadScene: "Load scene",
      loadSceneTitle: "Load the selected scene into the form below",
      saveSceneMetadata: "Save scene metadata",
      saveSceneMetadataTitle: "Save metadata for the selected scene",
      sceneStatusAria: "Scene status",
      previousScenePlaceholder: "Previous scene ID",
      povCharacterPlaceholder: "POV character ID",
      locationPlaceholder: "Location ID",
      timelinePlaceholder: "Timeline",
      sceneGoalPlaceholder: "Scene goal",
      sceneConflictPlaceholder: "Scene conflict",
      sceneOutcomePlaceholder: "Scene outcome",
      emotionalTurnPlaceholder: "Emotional turn",
      stylePovPlaceholder: "Style POV",
      tensePlaceholder: "Tense",
      tonePlaceholder: "Tone",
      rhythmPlaceholder: "Sentence rhythm",
      dictionPlaceholder: "Diction",
      dialogueStylePlaceholder: "Dialogue style",
      bannedPatternsPlaceholder: "Banned patterns, one per line",
      requiredCharactersPlaceholder: "Character IDs, one per line",
      mustIncludePlaceholder: "Required elements, one per line",
      mustNotViolatePlaceholder: "Constraints, one per line",
      storyBibleTitle: "Characters / Locations / Rules",
      characterNamePlaceholder: "Character name",
      characterRolePlaceholder: "Character role",
      createCharacter: "Character",
      locationNamePlaceholder: "Location name",
      locationTypePlaceholder: "Location type",
      createLocation: "Location",
      ruleDomainPlaceholder: "Rule domain",
      worldRulePlaceholder: "World rule",
      createRule: "Rule",
      importedPovLabel: "POV hint",
      importedLocationLabel: "Location hint",
      matchedPrefix: "Matched",
      useExisting: "Use existing",
      useExistingTitle: "Fill the current scene form without saving scene metadata",
      fillCharacter: "Fill character",
      fillCharacterTitle: "Fill the character seed form without writing canon",
      fillLocation: "Fill location",
      fillLocationTitle: "Fill the location seed form without writing canon",
      footer: "Imports, drafts, and candidate facts never rewrite canon directly."
    },
    editor: {
      contextButton: "Context",
      saveButton: "Save",
      generateDraftButton: "Generate draft only",
      generateDraftTitle: "Build context, generate scene prose, and save only to the draft store.",
      runWorkflowButton: "Run scene workflow",
      runWorkflowTitle: "Write from scene canon and context, then run continuity and candidate-fact extraction. Project sources are never loaded automatically.",
      goal: "Goal",
      pov: "POV",
      conflict: "Conflict",
      timeline: "Timeline",
      location: "Location",
      draftTitle: "Scene draft",
      unsavedDraft: "Unsaved local draft",
      draftBodyAria: "Scene draft body",
      draftSummaryAria: "Draft summary",
      markSelectionForAgent: "Mark for Agent",
      markSelectionForAgentTitle: "Send the latest selected draft span to Agent discussion",
      runTitle: "Agent run",
      runNotStarted: "Not started"
    },
    agentDiscussion: {
      ariaLabel: "Agent discussion",
      title: "Agent discussion",
      description: "Create a non-canon proposal from the current scene, selected text, explicitly selected project sources, and optional web search.",
      llmConfigured: "Model configured",
      llmNotConfigured: "Model not configured",
      mode: "Mode",
      modes: { discuss: "Discuss", revise_selection: "Revise selection", revise_scene: "Revise full scene" },
      useDraftSelection: "Use draft selection",
      instructionLabel: "What would you like to discuss?",
      instructionPlaceholder: "For example: make this emotional turn more restrained while preserving the POV boundary.",
      selectionLabel: "Marked text",
      selectionPlaceholder: "Select text in the draft and click “Use draft selection,” or paste text here.",
      submit: "Send to Agent",
      openProposal: "Open proposals",
      includeContextPack: "Include context pack",
      includeLatestDraft: "Include current draft",
      allowWebSearch: "Web search",
      webSearchPlaceholder: "Search terms; leave empty to use the question",
      noSceneTitle: "Select a scene first",
      noSceneText: "Agent discussion is bound to the current scene and saves its result as a proposal.",
      proposalMetric: "Created proposal",
      replacementMetric: "Replacement status",
      fullSceneDraft: "Full scene proposal created",
      discussionOnly: "Discussion only / draft unchanged",
      truncatedSources: "Truncated sources",
      webResults: "Search results",
      revisionNeedsDraft: "Revision modes require the current draft. Switch to Discuss if you do not want to send it.",
      sourcePickerTitle: "Project sources for this request",
      sourcePickerCount: (count: number) => `${count} explicitly selected`,
      sourcePickerDefault: "No sources are selected by default",
      sourcePickerAria: "Project sources available to the Agent",
      sourcePickerEmpty: "No selectable project sources. Import one under Sources first.",
      sourcePickerSafety: "Only explicitly selected, successfully extracted sources are sent. Chinese and English sources are never mixed or translated automatically."
    },
    settings: {
      desktopBackend: "Desktop backend",
      apiAddress: "API address",
      configuredWorkspace: "Configured workspace",
      backendStatus: "Status",
      healthWorkspace: "Health-check workspace",
      process: "Process",
      notReturned: "Not returned",
      notConnected: "Not connected",
      externalOrUnknownProcess: "External or unknown process",
      notRunning: "Not running",
      managedProcess: "Managed",
      externalProcess: "External",
      externalBackendWarning: "This is an external backend. Closing the desktop shell will not stop it.",
      refreshBackend: "Refresh backend",
      startOrConnect: "Start / Connect",
      stopManagedBackend: "Stop managed backend",
      modelSection: "Core model",
      writerMode: "Writing mode",
      ruleBasedMode: "Local rule-based mode",
      llmMode: "OpenAI-compatible model",
      providerName: "Provider name",
      baseUrl: "Base URL",
      model: "Model",
      requestJsonMode: "Request JSON mode",
      apiKeySection: "API key",
      currentKey: "Current key",
      configuredKey: "Configured",
      hiddenKey: "Hidden",
      replaceKey: "Replace key",
      keyPlaceholder: "Leave blank to keep the existing key",
      clearKey: "Clear saved key",
      permissionSection: "Permission level",
      permissionWarning: "Changes apply immediately. Canon writes still require full backend permission and human provenance.",
      versionSection: "Version and updates",
      currentVersion: "Current version",
      publishedAt: "Published",
      desktopUpdateNote: "The desktop app uses signed Tauri updates. The web app only links to the latest GitHub Release installer.",
      installUpdate: "Install and restart",
      downloadInstaller: "Download installer",
      refreshSettings: "Refresh",
      checkUpdates: "Check for updates",
      saveSettings: "Save settings"
    },
    runtime: {
      updateIdle: "Updates have not been checked.",
      updateChecking: "Checking for updates…",
      desktopUpdateAvailable: (version: string) => `Version ${version} is available for in-app installation and restart.`,
      installerUpdateAvailable: (version: string) => `Version ${version} is available as a Windows installer.`,
      updateCurrent: (version: string) => `Version ${version} is current.`,
      updateChannelUnavailable: "The desktop update channel is temporarily unavailable.",
      noGithubRelease: "No newer installer is published. You can continue using this version.",
      invalidGithubRelease: "The latest release has no valid version number.",
      updateCheckFailed: "Updates could not be checked right now.",
      noInstallableUpdate: "No installable desktop update is available. Check for updates first.",
      installingUpdate: (version: string) => `Downloading and installing v${version}. The app will restart when finished.`,
      installedRestarting: "Update installed. Restarting the app.",
      installedManualRestart: "The update is installed, but automatic restart failed. Quit and reopen the app to finish updating.",
      backendRecovered: "The local backend was restored. You can keep working.",
      backendRecoveredIncompatible: "The local backend started, but its workspace is incompatible.",
      backendRecoveryFailed: "The local backend could not be restored.",
      updateInstallFailed: "Update installation failed.",
      backendStopExternal: "The managed backend was asked to stop, but an external backend is still running.",
      backendStopped: "The managed backend stopped.",
      backendNotConnected: "Backend not connected",
      backendWorkspaceConflict: "Backend workspace conflict",
      backendManaged: "Managed backend",
      backendExternal: "External backend",
      backendConnectedManaged: "Connected, desktop-managed",
      backendConnectedExternal: "Connected, external process",
      modelKeyMissing: "Model API key not configured",
      localRules: "Local rules",
      apiAddressAria: "API address",
      archiveDemo: (nodes: number, relationships: number) =>
        `Bundled demo removed: archived ${nodes} nodes and ${relationships} relationships.`,
      draftSaved: (version: number) => `Draft v${version} saved.`,
      draftGenerated: (version: number) => `Draft v${version} generated.`,
      workflowStatus: (status: string) => `Workflow status: ${status}.`,
      proposalSaved: (version: number) => `Proposal saved as v${version}. Drafts, candidate facts, and canon are unchanged.`,
      proposalCreated: (version: number) => `Proposal created as v${version}. It has not entered drafts, candidate facts, or canon.`,
      proposalRevised: (version: number) => `The Agent revised the proposal to v${version}. The current scene draft was not overwritten.`,
      factDraftCreated: (count: number) => count
        ? `Created a fact-draft proposal with ${count} candidate previews.`
        : "Created a fact-draft proposal; no candidate facts were found.",
      proposalSubmitted: (id: string) => `Proposal ${id} is ready for review.`,
      proposalDecided: (accepted: boolean) => `Proposal ${accepted ? "accepted" : "rejected"}; canon is unchanged.`,
      proposalPromoted: (version: number) => `Promoted to current scene draft v${version}; canon is unchanged.`,
      structureApplied: (chapters: number, scenes: number, reused: boolean) => reused
        ? `This structure was already applied: reused ${chapters} chapters and ${scenes} scenes; canon facts are unchanged.`
        : `Applied structure: created ${chapters} chapters and ${scenes} scenes; canon facts are unchanged.`,
      candidatesSubmitted: (count: number) => count
        ? `Submitted ${count} candidate facts; canon is unchanged.`
        : "No candidate facts were extracted from the source draft.",
      factReviewed: (action: string, resumed: boolean) =>
        `Candidate fact ${action}${resumed ? "; the paused workflow resumed" : ""}.`,
      characterCreated: (id: string, filled: boolean) =>
        `Character written as a canon seed: ${id}${filled ? "; the scene POV and required-character fields were filled and take effect when scene metadata is saved" : ""}.`,
      locationCreated: (id: string, filled: boolean) =>
        `Location written as a canon seed: ${id}${filled ? "; the scene location field was filled and takes effect when scene metadata is saved" : ""}.`
    },
    inspector: {
      noContextTitle: "No context pack",
      noContextText: "Build context to inspect canon, budget, and gaps.",
      budget: "Budget",
      graphQueries: "Graph queries",
      mustInclude: "Must include",
      mustNotViolate: "Must not violate",
      relationships: "Relationships",
      foreshadowing: "Foreshadowing",
      missingContext: "Missing context",
      droppedItems: "Dropped items",
      currentStep: "Current step",
      reviewPayload: "Review payload",
      continuity: "Continuity",
      blockingIssues: "Blocking issues",
      summary: "Summary",
      checkedDimensions: "Checked dimensions",
      issues: "Issues",
      suggestion: "Suggestion",
      noReportTitle: "No continuity report",
      noReportText: "Run the scene workflow to view continuity results.",
      runSteps: "Run steps",
      noFactsTitle: "No facts awaiting review",
      noFactsText: "Extracted state changes wait here for human review."
    },
    graph: {
      title: "Graph / Timeline",
      emptyTitle: "No backend graph preview",
      emptyText: "Select a real project to preview canon graph relationships and its scene timeline.",
      noRelationships: "No relationships to preview.",
      truncated: "Preview truncated to the first items.",
      noScenes: "No scenes"
    },
    notices: {
      sourceImportNoSelection: "No files selected for import.",
      sourceImportFinished: "Source import finished. Detailed results remain on the Sources page.",
      sourceRetryFinished: "Source retry finished and results were refreshed.",
      sourceSavedAsDraft: (title: string, version: number) => `“${title}” was explicitly saved as current scene draft v${version}.`,
      sourceSavedAsStyle: (title: string) => `“${title}” was explicitly saved as a style sample.`,
      sourceSavedAsProposal: (title: string) => `“${title}” was explicitly saved to the proposal workspace.`,
      sourceStructureCreated: (chapters: number, scenes: number, truncated: boolean) =>
        `Created a structure proposal with ${chapters} chapters and ${scenes} scenes${truncated ? " from truncated input" : ""}. The project tree is unchanged.`,
      sourceArchived: (title: string) => `“${title}” was archived. Stable source references remain valid.`,
      agentSourceLimit: "A request can use at most 32 project sources.",
      settingsSaved: "Agent settings saved.",
      projectCreated: "Project created. You can import a manuscript and propose its chapter/scene structure.",
      projectUpdated: "Project details updated.",
      chapterUpdated: "Chapter metadata updated.",
      chapterCreated: "Chapter written as a canon seed.",
      sceneCreated: "Scene created. You can save a draft or run the Agent workflow.",
      sceneUpdated: "Scene metadata updated. You can rebuild the context pack.",
      worldRuleCreated: "World rule written as a canon seed.",
      contextRefreshed: "Context pack refreshed.",
      openedFactReview: "Candidate-fact review opened.",
      agentSceneDraftCreated: "The Agent created a scene-draft proposal. The current scene draft was not overwritten.",
      agentDiscussionCreated: "The Agent created a discussion record. Review it in the proposal workspace.",
      draftSelectionRequired: "Select a span in the scene draft first.",
      updateInstalledRestarting: "Update installed. Restarting the app."
    },
    errors: {
      selectProjectOrCreate: "Select or create a project first.",
      selectProject: "Select a project first.",
      projectNameRequired: "Enter a project name first.",
      projectNameNotEmpty: "Project name cannot be empty.",
      projectLanguageRequired: "Choose Chinese or English as the story language.",
      chooseChapterForEdit: "Select a chapter to edit.",
      chapterTitleRequired: "Enter a chapter title.",
      chooseChapter: "Select a chapter first.",
      sceneTitleRequired: "Enter a scene title.",
      chooseSceneForEdit: "Select a scene to edit.",
      characterNameRequired: "Enter a character name.",
      locationNameRequired: "Enter a location name.",
      worldRuleRequired: "Enter both a rule domain and rule text.",
      selectScene: "Select a scene first.",
      agentInstructionRequired: "Enter a question or instruction for the Agent.",
      agentSelectionRequired: "Enter or select the text to revise.",
      agentRevisionRequiresSavedDraft: "Save the current draft before asking the Agent to revise the scene or selection.",
      selectProjectAndScene: "Create and select a project and scene first.",
      selectSceneForDraft: "Create and select a scene first.",
      selectProjectForStyle: "Create and select a project first.",
      sourceNotReadyStructure: "Only successfully extracted sources can create a structure proposal.",
      sourceDetailNotReady: "The full source text has not loaded successfully.",
      sourceEmptyText: "The file contains no usable text.",
      sourceUnsafePath: "The relative file path is unsafe, so import was stopped.",
      sourceUnsupportedFormat: "Only TXT, Markdown, and DOCX are supported right now. This file was not imported.",
      sourceRetryFormatMismatch: "The retry file format does not match the original source.",
      webCryptoUnavailable: "This runtime cannot calculate SHA-256, so the file cannot be imported safely.",
      docxExtractionFailed: (detail: string) => `DOCX text extraction failed: ${detail}`,
      documentNotReadyDraft: "This source cannot be saved as a draft yet.",
      documentNotReadyStyle: "This source cannot be saved as a style sample yet.",
      documentNotReadyStructure: "This source cannot create a structure proposal yet.",
      documentNotReadyFacts: "This source cannot extract facts yet.",
      documentNotReadyProposal: "This source cannot be saved as a proposal yet.",
      selectProposal: "Select a proposal first.",
      selectProjectStructureProposal: "Select a project structure proposal first.",
      selectSceneAndProposal: "Select both a scene and proposal first.",
      sourceDraftRequired: "Enter a real source draft ID.",
      workflowMissingDraft: "The workflow did not return a draft-store draft.",
      noInstallableDesktopUpdate: "No installable desktop update is available. Check for updates first.",
      requestFailed: "The operation did not finish. Expand technical details, then try again.",
      technicalDetails: "Technical details",
      sourceLanguageRequired: "Set this source language to Chinese or English first.",
      sourceContentLanguageMismatch: "Only a source in the story language can be copied directly into a draft, proposal, or style sample. Other-language sources may only be analyzed as explicit Agent references.",
      mixedLanguageStructure: "Structure analysis uses sources in the story language by default. Other-language sources require explicit reference mode and are never translated automatically."
    }
  },
  demoText: identityDemoText,
  statuses: {
    idle: "Idle", ready: "Ready", pending: "Pending", planned: "Planned", drafting: "Drafting",
    archived: "Archived", running: "Running", completed: "Completed", pass: "Pass",
    awaiting_review: "Awaiting review", needs_revision: "Needs revision", blocked: "Blocked",
    failed: "Failed", skipped: "Skipped", inconclusive: "Inconclusive", accepted: "Accepted",
    rejected: "Rejected", deferred: "Deferred", edited: "Edited", none: "None", "not checked": "Not checked"
  },
  severities: { critical: "Critical", high: "High", medium: "Medium", low: "Low" },
  dimensions: {
    knowledge_boundary: "Knowledge boundary", timeline: "Timeline", location_state: "Location state",
    relationship_state: "Relationship state", world_rule: "World rule", foreshadowing: "Foreshadowing",
    causality: "Causality", pov: "Point of view", style_constraint: "Style constraint"
  },
  issueTypes: {
    knowledge_boundary_violation: "Knowledge-boundary violation", timeline_conflict: "Timeline conflict",
    location_conflict: "Location conflict", relationship_conflict: "Relationship conflict",
    world_rule_conflict: "World-rule conflict", missing_required_element: "Missing required element",
    unsupported_new_fact: "Unsupported new fact", style_drift: "Style drift",
    foreshadowing_mismatch: "Foreshadowing mismatch", causal_gap: "Causal gap", pov_leak: "POV leak"
  },
  steps: {
    build_context: "Build context", write_draft: "Write draft", check_continuity: "Check continuity",
    extract_state: "Extract state", human_review: "Human review"
  },
  proposalTypes: {
    scene_draft: "Scene draft", fact_draft: "Fact draft", scene_rebuild: "Scene rebuild",
    canon_patch: "Canon patch", outline_draft: "Outline draft", project_structure_draft: "Project structure draft"
  },
  proposalStatuses: {
    drafting: "Drafting", agent_revised: "Agent revised", author_revised: "Author revised",
    ready_for_review: "Ready for review", accepted: "Accepted", rejected: "Rejected"
  },
  permissions: {
    labels: { read_only: "Read only", read_generate: "Read and generate", full: "Full permission" },
    descriptions: {
      read_only: "Read canon, drafts, proposals, context packs, runs, and pending facts only.",
      read_generate: "Read and create drafts, proposals, checks, candidate facts, and style samples.",
      full: "Allow full local author actions, including manual seeds, proposal decisions, and candidate-fact review."
    }
  },
  reviewActions: { accept: "Accept", reject: "Reject", defer: "Defer" },
  refKinds: {
    author_instruction: "Author instruction", imported_document: "Imported document", source_document: "Project source",
    draft: "Draft", scene: "Scene", chapter: "Chapter", graph_node: "Graph node", graph_relation: "Graph relationship",
    candidate_fact: "Candidate fact", context_pack: "Context pack", continuity_report: "Continuity report",
    workflow_run: "Workflow run", style_sample: "Style sample", proposal_artifact: "Proposal"
  },
  provenanceMethods: { manual: "Manual", llm: "Model-generated", import: "Imported", workflow: "Workflow", api: "API" },
  knownMessages: { "Human review completed.": "Human review completed." }
} satisfies LocaleCatalog;
