export const zhCN = {
  locale: "zh-CN",
  app: {
    documentTitle: "StoryGraph 写作台",
    brandName: "StoryGraph Agent",
    tagline: "长篇小说安全写作台"
  },
  terms: {
    agent: "智能体",
    api: "API",
    candidateFact: "候选事实",
    canon: "正典",
    canonReview: "正典审阅",
    canonSeed: "正典初始化",
    contextPack: "上下文包",
    draftStore: "草稿库",
    factDraft: "事实草稿",
    fastApi: "本地后端",
    graphStore: "正典图谱",
    githubRelease: "软件发布页",
    llm: "大模型",
    proposalStore: "协作提案库",
    reviewService: "审阅服务",
    styleSampleStore: "风格样本库",
    tauri: "桌面版"
  },
  contentDefaults: {
    genre: "奇幻",
    narrativePov: "第三人称有限视角",
    untitledProposal: "未命名协作草稿",
    proposalSuffix: "协作草稿"
  },
  ui: {
    manuscript: {
      saveWholeSource: "整份资料另存为正文", sourceAdvanced: "资料高级操作",
      localBackendOnly: "此操作需要本地 JSON 或内存图谱后端。当前连接不支持安全应用。", compositionTooLarge: "选中的资料和正文超过 10 万字符。请减少参考资料后重试。", compositionInvalid: "结构与正文提案不符合格式或语言要求。请调整要求后重新生成。", compositionStale: "目录、卷位置或作品语言已经变化。请刷新目录并重新生成这份提案。", sourceStale: "资料已更新，请重新打开并选择原文。",
      staleProposal: "当前正文已不是这份建议依据的版本。请保留当前正文，并以最新已保存版本重新让 Agent 修改。",
      includeSelectedSources: "包含已明确选中的资料",
      includeCurrentDraft: "将当前已保存正文作为参考", compositionInputs: "输入：作品与现有目录。资料和正文仅在明确选择后加入。",
      lineBreak: "换行",
      preview: "预览", edit: "编辑", chapterPreview: "章节正文", sceneBody: "场景正文", openScene: "打开场景", editChapter: "编辑章节信息",
      emptyTitle: "这一场还没有正文", emptyHelp: "目录与摘要是写作计划，正文需要另行写入。你可以自己动笔、让 Agent 起草，或从资料中选取原文。", startWriting: "开始写作", generateScene: "让 Agent 起草", openSources: "查看原稿 / 导入资料", loading: "正在读取正文…", loadFailed: "正文读取失败，请刷新重试。",
      chapterHelp: "按目录顺序阅读各场景。选中文字可以交给 Agent，编辑正文请打开对应场景。", chapterEmpty: "本章尚未建立场景。可在左侧添加场景，或让 Agent 规划下一章。", sceneEmpty: "此场景尚无正文", selectionAction: "就选区问 Agent", selectionChanged: "正文版本已变化，请重新选择要讨论的段落。", readingDraft: "已保存草稿", unsavedPreview: "预览包含尚未保存的修改，发送给 Agent 前请先保存。", selectionHelp: "选中一段文字，即可提问或提出修改要求。",
      diffTitle: "正文修改对比", added: "增加", removed: "删除", unchanged: "保留", noChanges: "正文没有变化", simplified: "文本较长，以下按完整文本显示差异。",
      newWork: "新章节 / 卷", currentScene: "当前场景", generationHelp: "描述接下来要发生的故事。Agent 会先生成可审阅的结构和正文草稿，接受并应用后才加入目录。", scope: "创作范围", chapter: "新章节", volume: "新卷", chapterCount: "章节数", sceneCount: "每章场景数", instruction: "这部分故事要写什么", instructionPlaceholder: "例如：下一章让主角抵达火星基地，发现补给记录被人篡改。保持当前叙事视角。", generate: "生成结构与正文草稿", noProject: "先创建或选择作品。", compositionTitle: "结构与正文草稿", volumeLabel: "卷标题", plannedProse: "待审正文", applyComposition: "加入目录与草稿", compositionApplied: "已加入目录与草稿", compositionCreated: "结构与正文提案已生成，请逐章审阅。", compositionHelp: "接受只记录你的决定；点击“加入目录与草稿”后才会新增章节和场景。现有正文不会被替换。", sourceOriginal: "资料原文 · 尚未作为正文", useSource: "选取原文作为正文", sourceHelp: "这里只展示关联资料，不会自动把整份资料当作当前场景。请选中本场景的原文后再存为草稿。"
    },
    authorWorkspace: {
      treeTitle: "作品",
      toggleChapter: (title: string) => `展开或折叠章节：${title}`,
      editChapterTitle: "编辑章节标题与属性",
      editingChapter: "正在编辑章节",
      discardChapterEdits: "章节标题或属性尚未保存。放弃这些修改并继续？选择取消可以返回保存。",
      discardMetadataEdits: "标题或属性尚未保存。放弃这些修改并继续？选择取消可以返回保存。",
      chapterTargetRequired: "请先载入要编辑的章节属性。",
      chapterTitle: "章节标题",
      renameScene: "修改场景标题",
      sceneTitle: "场景标题",
      chapterSavedExplicitly: "修改标题后点击保存；正文保持不变。",
      chapterDetails: "更多章节属性",
      openScene: (title: string) => `打开正文：${title}`,
      openAgent: "打开智能体",
      closeAgent: "收起侧栏",
      agentTitle: "写作助手",
      draftContext: "本次输入",
      inputDetails: "完整输入清单",
      referenceOptions: "资料与高级选项",
      presetOptions: "写作预设",
      reviewResult: "查看与比较提案",
      resultReady: "建议已准备好，等待你审阅",
      resultBoundary: "建议还没有替换正文。比较后可接受并采用。",
      saveBeforeSend: "正文有未保存修改。请先保存，再让智能体读取这个版本。",
      saveCurrentDraft: "保存当前正文",
      sceneProperties: "场景属性",
      versionsAndLanguage: "版本与内容语言",
      workspaceDetails: "工作区状态",
      projectDetails: "作品信息",
      writingGuide: "直接写作，或在右侧请求续写与修改。智能体建议由你决定是否采用。",
      settingsTitle: "设置与检查"
    },
    genres: { fantasy: "奇幻", science_fiction: "科幻", sci_fi: "科幻", romance: "言情", mystery: "悬疑", thriller: "惊悚", historical: "历史", horror: "恐怖", adventure: "冒险", literary: "文学", wuxia: "武侠", xianxia: "仙侠", urban: "都市", other: "其他" },
    navigation: {
      backendVersion: "后端版本",
      backendVersionUnknown: "未能确认后端版本",
      backendVersionLegacy: "旧版后端：版本来自 OpenAPI",
      backendVersionMismatch: (app: string, backend: string) => `版本不一致：界面 ${app}，后端 ${backend}。安装可能未完整更新，请关闭应用后重新运行最新安装器。`,
      backendVersionUnknownHelp: "后端版本尚未确认；界面的更新检查不能证明整个安装已经完整更新。",
      tools: "工具与检查",
      toolsHelp: "设置、工作流、连续性与正典审阅",
      closeInspector: "收起检查面板",
      sceneDetails: "场景目标与细节",
      connection: "后端连接",
      connect: "连接",
      connectionFailed: "无法连接本地后端",
      connectionFailedHelp: "项目尚未载入。请确认后端已经启动，或在设置中修改后端连接地址，然后刷新。",
      workflowHelp: "依次构建上下文、生成草稿、检查连续性、抽取候选事实；最终由你审阅。",
      startWorkflow: "运行完整工作流",
      welcomeTitle: "开始你的故事",
      welcomeText: "创建项目 → 导入小说或添加场景 → 写作与智能体协作 → 审阅后采用。",
      writeHelp: "在这里写正文。保存后可让智能体续写或修改，结果先进入协作草稿。",
      sourcesHelp: "导入小说或设定资料；选中资料后可生成章节结构，或带入智能体对话。",
      agentHelp: "说明要续写或修改的内容，检查输入清单后发送。结果由你审阅采用。",
      proposalsHelp: "检查和编辑智能体建议。接受后，可明确转为场景草稿；事实另行审阅。",
      setupModel: "配置模型",
      continueScene: "续写",
      continueInstruction: "续写指令",
      exportText: "导出文本",
      modelDiscovery: "刷新可用模型",
      modelDiscoveryHelp: "使用已保存的 API 地址与密钥读取服务商模型列表；选择模型后保存设置。",
      modelsUnavailable: "服务商没有返回模型列表。仍可手动填写模型名。",
      currentModelUnavailable: "当前模型不在服务商返回的列表中，请选择可用模型并保存。",
      draftCharacters: (count: number) => `${count.toLocaleString("zh-CN")} 字符`,
      draftUnsaved: "有未保存修改",
      draftSaved: "已保存",
      unsavedDraftTitle: "正文还有未保存修改",
      unsavedDraftText: (destination: string) => `在${destination}前，请保存或放弃当前正文与摘要修改。`,
      editsDuringSave: "刚才的版本已保存。保存期间的新修改仍在编辑器中，请再次保存后继续。"
    },
    presets: {
      title: "Agent 预设",
      select: "当前写作预设",
      help: "预设用于之后的生成、续写与修改，保存在本机工作区。切换预设后立即生效。",
      systemPrompt: "系统提示词（System prompt）",
      preview: "查看系统提示词",
      manage: "管理预设",
      create: "新建预设",
      edit: "编辑预设",
      duplicate: "复制并编辑",
      delete: "删除预设",
      deleteConfirm: (name: string) => `删除预设“${name}”？使用中的自定义预设删除后会恢复“中文简练”。`,
      name: "预设名称",
      description: "用途说明",
      saved: "预设已保存。",
      selected: "写作预设已切换。",
      deleted: "预设已删除。",
      builtin: "内置",
      custom: "自定义",
      bounds: "系统提示词最多 12,000 字符。预设不能更改小说输出语言或绕过人工审阅。",
      builtin_zh_concise: { name: "中文简练", description: "中文写作时少用状语，优先用具体动作和准确动词。" },
      builtin_balanced: { name: "均衡叙事", description: "兼顾人物、情节节奏和细节，保持叙事连贯。" },
      builtin_en_precise: { name: "英文精炼", description: "英文写作优先使用准确动词和具体细节，减少冗余修饰。" }
    },
    common: {
      all: "全部",
      cancel: "取消",
      checking: "正在检查...",
      create: "创建",
      missing: "缺失",
      none: "无",
      loading: "读取中",
      newItem: "新建",
      notConfigured: "未配置",
      refresh: "刷新",
      save: "保存",
      undo: "撤销",
      redo: "重做",
      writing: "写作",
      notCreated: "未创建",
      notSet: "未设置"
    },
    language: {
      uiLocaleLabel: "界面语言",
      chinese: "简体中文",
      english: "English",
      projectLanguageLabel: "小说内容语言",
      projectLanguageHelp: "只控制这个项目的新内容与智能体输出；切换界面语言不会改动小说。",
      projectLanguageNeedsReview: "原语言值需要作者确认",
      projectLanguageChangeConfirm: "只把新语言用于今后的生成结果？已有草稿、提案、资料和正典不会被翻译或修改。",
      sourceLanguageLabel: "资料语言",
      artifactLanguageLabel: "内容语言快照",
      historicalLanguageUnknown: "历史记录未保存语言",
      inferredLanguage: "（历史推断）",
      detectedChinese: "检测为中文",
      detectedEnglish: "检测为英文",
      detectedUnknown: "无法确定语言",
      undetermined: "未确定（不可用于智能体）",
      editSourceLanguage: "修正语言",
      saveSourceLanguage: "保存语言",
      projectOnly: "仅同语言资料",
      explicitReference: "显式参考异语资料",
      explicitReferenceHelp: "只把明确勾选的异语资料作为参考；不会自动翻译，输出仍使用小说内容语言。",
      sourceMismatchDisabled: "资料语言与小说内容语言不同；请开启“显式参考异语资料”后再逐项选择。",
      sourceUnknownDisabled: "语言未确定的资料不能用于智能体或项目结构分析，请先在资料详情修正。"
    },
    commandBar: {
      ariaLabel: "全局命令",
      saveDraftTitle: "保存当前场景草稿",
      undoTitle: "撤销当前输入框编辑",
      redoTitle: "重做当前输入框编辑",
      refreshTitle: "刷新后端项目树",
      sourcesTitle: "打开当前项目的持久资料库",
      agentTitle: "打开智能体对话",
      proposalsTitle: "打开协作草稿箱",
      runTitle: "根据当前正典和上下文运行场景写作工作流"
    },
    tabs: {
      write: "写作",
      sources: "资料",
      agent: "智能体对话",
      proposals: "协作草稿",
      workflow: "工作流",
      context: "上下文",
      continuity: "质检",
      facts: "事实",
      settings: "设置"
    },
    stateStrip: {
      projectPrefix: "项目",
      writerPrefix: "写作器",
      llmIncomplete: "大模型设置未完整",
      safetyBoundary: "草稿、候选事实、正典分离"
    },
    workspace: {
      emptyTitle: "当前后端没有真实项目",
      emptyText: "请先创建自己的小说项目；创建后可导入已有小说，让智能体生成章节和场景结构草稿。",
      importedStructureTitle: "导入小说生成项目结构",
      emptyWorkspaceTitle: "空工作区",
      noSceneWithWorkspace: "可在“资料”导入已有小说并生成结构，或展开左侧“章节/场景”手动新建。",
      noSceneEmptyWorkspace: "先创建项目，再导入已有小说或新建章节与场景。",
      sceneMetadataAria: "场景元数据",
      mainWorkspaceAria: "主工作区",
      workflowStatusAria: "当前工作流状态"
    },
    library: {
      ariaLabel: "项目资料库",
      title: "项目资料库 / 导入",
      summary: (count: number) => `${count} 个项目资料 · 后端持久保存 · 非正典`,
      fileButton: "导入文件",
      folderButton: "导入文件夹",
      refreshButton: "刷新资料",
      emptyTitle: "当前项目还没有资料",
      emptyText: "可按原目录导入 TXT、Markdown 或 DOCX；导入结果会保存在当前项目，重启后仍可读取。",
      readerEmptyTitle: "选择一份项目资料",
      readerEmptyText: "列表只读取摘要；选择后才会从后端加载全文。阅读和导入都不会自动写入草稿、协作提案、候选事实或正典。",
      readerLoadingTitle: "正在读取资料全文",
      readerLoadingText: "全文只在你明确打开这份资料时加载。",
      readerLoadFailedTitle: "资料全文尚未载入",
      readerLoadFailedText: "请重新选择资料或点击“刷新资料”后再试。",
      bridgeText: "下面都是显式操作：只有点击对应按钮，才会把已加载全文写入草稿、协作提案、风格样本，或生成项目结构草稿；不会直接改变正典。",
      useWithAgent: "带入智能体",
      useWithAgentTitle: "仅为本次智能体请求选中这份资料的稳定 ID，然后打开智能体；此时不会复制资料正文。",
      useWithAgentMismatchTitle: "选中这份异语资料并打开智能体；在你主动启用显式参考异语资料前，发送会保持阻止。",
      useWithAgentNotReady: "这份资料尚未成功提取，不能选为智能体输入。",
      buildStructure: "生成项目结构草稿",
      buildStructureTitle: "从导入小说生成可编辑的项目结构草稿；作者确认后才会创建章节/场景。",
      saveDraft: "设为当前草稿",
      saveDraftTitle: "保存为当前场景草稿库草稿，不写正典。",
      saveProposal: "存入草稿箱",
      saveProposalTitle: "保存为协作提案库草稿，不写当前场景草稿。",
      saveStyle: "存为风格样本",
      saveStyleTitle: "保存为风格样本库样本，只作为较低优先级的软参考。",
      retry: "重试抽取",
      retryTitle: "重新选择原文件；相同路径和校验值会复用稳定资料编号，并尝试修复失败记录。",
      archive: "归档资料",
      archiveTitle: "从当前项目的常规资料列表中归档；不是删除，已有来源引用仍保留。",
      archiveConfirm: (title: string) => `确定归档“${title}”吗？归档不是删除，但它将不再出现在常规资料列表中。`,
      readErrorTitle: "这份资料的文本抽取失败。",
      unknownReadError: "后端没有返回具体错误，请重新导入原文件。",
      sourceWarningTitle: "资料抽取完成，但有技术提示。",
      resizeHeightAria: "调整资料面板高度",
      resizeWidthAria: "调整资料列表与详情宽度",
      resizeHelp: "拖动调整；方向键微调，Shift 加速，Home/End 到边界，双击恢复默认。",
      localRoot: "项目资料",
      importProgress: (current: number, total: number) => `正在按顺序导入 ${current} / ${total}`,
      importComplete: "本轮导入完成",
      importCreated: (count: number) => `新增 ${count}`,
      importUpdated: (count: number) => `更新 ${count}`,
      importUnchanged: (count: number) => `未变化 ${count}`,
      importFailed: (count: number) => `失败 ${count}`,
      importSkipped: (count: number) => `跳过 ${count}`,
      importProvenanceNote: "作者从项目资料页导入。",
      redactedLocalPath: "[已隐藏本机路径]",
      importedDraftSummaryPrefix: "从项目资料显式设为草稿：",
      importedStyleSummaryPrefix: "从项目资料显式保存的风格样本：",
      importedProposalTitlePrefix: "导入资料协作稿：",
      importedProposalNotePrefix: "作者从项目资料显式创建协作稿：",
      formats: {
        txt: "TXT",
        markdown: "Markdown",
        docx: "DOCX"
      }
    },
    proposals: {
      ariaLabel: "协作草稿箱",
      title: "协作草稿箱",
      countSuffix: "条 / 协作提案库",
      filterAria: "协作草稿状态筛选",
      emptyTitle: "暂无协作草稿",
      emptyText: "可从项目资料、智能体工作流或手动编辑创建。",
      typeAria: "协作草稿类型",
      titleAria: "协作草稿标题",
      titlePlaceholder: "标题",
      bodyAria: "协作草稿正文",
      save: "保存草稿",
      submitReview: "提交审阅",
      accept: "接受",
      reject: "拒绝",
      promoteDraft: "转为当前场景草稿",
      applyStructure: "应用为章节/场景",
      sourceDraft: "来源草稿",
      sourceDraftPlaceholder: "来源草稿编号",
      extractCandidates: "提交为候选事实",
      openCanonReview: "打开正典审阅",
      refsSource: "来源",
      refsTarget: "影响范围",
      refsDerived: "派生",
      metadataStatus: "状态",
      metadataType: "类型",
      metadataVersion: "版本",
      metadataCreatedVia: "创建方式",
      unselected: "未选择",
      newVersion: "新建",
      unsavedBadge: "有未保存修改",
      dirtyActionHelp: "请先保存或放弃标题和正文修改，再改变提案状态。",
      navigateRefresh: "刷新工作区",
      navigateProject: (title: string) => `切换到项目“${title}”`,
      navigateScene: (title: string) => `切换到场景“${title}”`,
      navigateProposal: (title: string) => `打开提案“${title}”`,
      navigateNewProposal: "新建提案",
      navigateCreateProject: "创建并切换到新项目",
      navigateCreateScene: "创建并切换到新场景",
      navigateArchiveDemo: "移除演示并刷新所选工作区",
      unsavedDialogTitle: "提案还有未保存修改",
      unsavedDialogText: (destination: string) => `在${destination}前，请保存或放弃当前提案修改。取消会原样保留所有编辑。`,
      saveAndContinue: "保存并继续",
      discardAndContinue: "放弃并继续",
      targetAmbiguous: "这份提案记录了多个场景目标，无法安全提升。",
      targetMissing: "这份提案没有记录唯一的场景目标，无法安全提升。",
      targetMismatch: (target: string) => `这份提案的目标是“${target}”，不是当前场景，因此无法提升。`,
      switchTarget: (title: string) => `切换到${title}`,
      legacyCurrentTarget: "兼容旧提案：它没有记录场景目标，因此提升时将显式使用当前所选场景。",
      derivedDraftAmbiguous: "完整性警告：记录了多个已提升草稿引用。系统不会任选或合并，且不会再次提升。",
      promotedDraftLoading: "正在加载精确的已提升草稿……",
      promotedDraftUnavailable: "这份提案记录了已提升草稿，但无法在精确的项目与场景范围内打开它。",
      alreadyPromoted: (id: string, version: number) => `已经提升：${id} / v${version}`,
      openPromotedDraft: "在写作中打开精确草稿",
      openDraftSwitchFirst: "这份精确草稿属于另一个场景。请先切换到该场景，再把它载入编辑器，避免保存到错误场景。",
      switchToDraftScene: "切换到草稿所属场景",
      draftAvailable: "可用",
      draftDiscarded: "已废弃",
      targetScene: "目标场景",
      reviewAria: "提案版本审阅",
      reviewTitle: "已保存版本审阅",
      reviewHelp: "查看持久化的提案版本及其精确记录的草稿基线；这里不会用未保存编辑替换正文。",
      historyTitle: "版本历史",
      versionContent: "查看此版本已保存正文",
      historicalTitle: "已保存标题",
      diffAria: "精确草稿与提案对比",
      diffTitle: "相对记录草稿的修改",
      diffHelp: "桌面并排显示，窄屏显示统一差异；作者正文绝不会被翻译。",
      baselineNone: "这个提案版本没有记录草稿基线；系统不会擅自改用当前或最新草稿。",
      baselineAmbiguous: "这个提案版本记录了多个草稿基线；系统不会任选或合并。",
      baselineTargetMissing: "这个提案版本没有唯一场景目标，因此无法打开精确草稿基线。",
      baselineLoading: "正在加载精确记录的草稿基线……",
      baselineUnavailable: "无法在这个项目与场景范围内打开精确记录的草稿基线。",
      baselineExact: (id: string, version: number) => `精确基线 ${id} / v${version}`,
      baselineColumn: "记录的草稿基线",
      proposalColumn: "已保存提案版本"
    },
    sidebar: {
      workspaceTitle: "真实工作区",
      projectTreeAria: "后端项目树",
      projectEmpty: "后端还没有项目。",
      projectLoading: "正在读取后端项目...",
      uncategorized: "未分类",
      languageUnset: "未设置语言",
      povUnset: "未设置视角",
      chapterCount: "章",
      sceneCount: "场景",
      refreshTitle: "从后端刷新项目树",
      createProject: "新建项目",
      createProjectTitle: "创建新的小说项目",
      editProject: "编辑项目",
      editProjectTitle: "编辑当前项目信息",
      archiveDemo: "移除演示",
      archiveDemoTitle: "仅移除内置演示项目，真实项目不受影响",
      requireFullPermission: "需要完全权限",
      noChapterScenes: "本章节还没有场景。",
      noProjectTreeTitle: "没有后端项目树",
      noProjectTreeText: "创建项目后，章节和场景会从正典图谱读取。",
      editProjectTitleText: "编辑项目信息",
      createProjectTitleText: "创建新的小说项目",
      projectNamePlaceholder: "项目名称",
      genrePlaceholder: "类型",
      languagePlaceholder: "语言",
      targetLengthPlaceholder: "目标篇幅",
      narrativePovPlaceholder: "叙述视角",
      saveProjectInfo: "保存信息",
      createProjectButton: "创建项目",
      outlineTitle: "章节 / 场景",
      chapterTitlePlaceholder: "章节标题",
      volumeIndexPlaceholder: "卷序号",
      chapterIndexPlaceholder: "章节序号",
      chapterStatusAria: "章节状态",
      addChapter: "添加章节",
      chapterPurposePlaceholder: "章节目的",
      chapterSummaryPlaceholder: "章节摘要",
      loadChapter: "载入当前章节",
      loadChapterTitle: "把当前选中的章节载入上方表单",
      saveChapterMetadata: "保存章节元数据",
      saveChapterMetadataTitle: "保存当前选中章节的元数据",
      chooseChapter: "选择章节",
      sceneTitlePlaceholder: "场景标题",
      sceneIndexPlaceholder: "场景序号",
      addScene: "添加场景",
      loadScene: "载入当前场景",
      loadSceneTitle: "把当前选中的场景载入下方表单",
      saveSceneMetadata: "保存场景元数据",
      saveSceneMetadataTitle: "保存当前选中场景的元数据",
      sceneStatusAria: "场景状态",
      previousScenePlaceholder: "前一场景编号",
      povCharacterPlaceholder: "视角人物编号",
      locationPlaceholder: "地点编号",
      timelinePlaceholder: "时间线",
      sceneGoalPlaceholder: "场景目标",
      sceneConflictPlaceholder: "场景冲突",
      sceneOutcomePlaceholder: "场景结果",
      emotionalTurnPlaceholder: "情绪转折",
      stylePovPlaceholder: "风格视角",
      tensePlaceholder: "时态",
      tonePlaceholder: "语气",
      rhythmPlaceholder: "句式节奏",
      dictionPlaceholder: "用词",
      dialogueStylePlaceholder: "对话风格",
      bannedPatternsPlaceholder: "禁用表达：每行一条",
      requiredCharactersPlaceholder: "出场人物编号：每行一条",
      mustIncludePlaceholder: "必须包含：每行一条",
      mustNotViolatePlaceholder: "禁止违反：每行一条",
      storyBibleTitle: "人物 / 地点 / 规则",
      characterNamePlaceholder: "人物名称",
      characterRolePlaceholder: "人物作用",
      createCharacter: "人物",
      locationNamePlaceholder: "地点名称",
      locationTypePlaceholder: "地点类型",
      createLocation: "地点",
      ruleDomainPlaceholder: "规则领域",
      worldRulePlaceholder: "世界规则",
      createRule: "规则",
      importedPovLabel: "视角提示",
      importedLocationLabel: "地点提示",
      matchedPrefix: "已匹配",
      useExisting: "使用已有",
      useExistingTitle: "只填入当前场景表单，不保存场景元数据",
      fillCharacter: "填入人物",
      fillCharacterTitle: "只填入人物初始化表单，不写入正典",
      fillLocation: "填入地点",
      fillLocationTitle: "只填入地点初始化表单，不写入正典",
      footer: "导入、草稿、候选事实都不会直接改写正典。"
    },
    editor: {
      contextButton: "上下文",
      saveButton: "保存",
      generateDraftButton: "仅生成草稿",
      generateDraftTitle: "仅执行构建上下文与写作草稿，并保存到草稿库。",
      runWorkflowButton: "运行场景写作工作流",
      runWorkflowTitle: "根据当前场景正典和上下文写场景草稿，再做质检和候选事实抽取。不会自动读取项目资料库。",
      goal: "目标",
      pov: "视角",
      conflict: "冲突",
      timeline: "时间线",
      location: "地点",
      draftTitle: "场景草稿",
      unsavedDraft: "本地未保存草稿",
      draftBodyAria: "场景草稿正文",
      draftSummaryAria: "草稿摘要",
      markSelectionForAgent: "标注给智能体",
      markSelectionForAgentTitle: "把最近选中的草稿片段带入智能体对话",
      runTitle: "智能体运行",
      runNotStarted: "尚未运行"
    },
    agentDiscussion: {
      ariaLabel: "智能体对话",
      title: "智能体对话",
      description: "围绕当前场景、选中文本、逐项选择的项目资料和可选联网搜索生成非正典协作提案。",
      llmConfigured: "大模型已配置",
      llmNotConfigured: "大模型未配置",
      mode: "模式",
      modes: {
        discuss: "讨论问题",
        revise_selection: "改写选中段落",
        revise_scene: "改写整场草稿"
      },
      useDraftSelection: "使用草稿选区",
      instructionLabel: "想和智能体讨论什么",
      instructionPlaceholder: "例如：这段情绪转折还不够自然，请保留视角限制并改得更克制。",
      selectionLabel: "标注片段",
      selectionPlaceholder: "从草稿中选择一段后点击“使用草稿选区”，也可以手动粘贴。",
      submit: "发送给智能体",
      openProposal: "打开草稿箱",
      includeContextPack: "包含上下文包",
      includeLatestDraft: "包含当前草稿",
      openWriting: "返回写作",
      restoreSavedDraft: "恢复已保存草稿",
      restoreDraftConfirm: "确定放弃本地草稿修改，并恢复精确的已保存草稿正文与摘要吗？",
      allowWebSearch: "联网搜索",
      webSearchPlaceholder: "搜索关键词；为空则使用问题文本",
      noSceneTitle: "请先选择场景",
      noSceneText: "智能体对话会绑定当前场景，并把结果保存为协作提案库草稿。",
      proposalMetric: "生成提案",
      replacementMetric: "替换状态",
      fullSceneDraft: "已生成完整场景草稿提案",
      discussionOnly: "讨论记录 / 未覆盖草稿",
      truncatedSources: "已截断资料",
      webResults: "搜索结果",
      revisionNeedsDraft: "改写模式必须包含当前草稿；若不希望发送草稿，请切换为“讨论问题”。",
      sourcePickerTitle: "本次使用的项目资料",
      sourcePickerCount: (count: number) => `已逐项选择 ${count} 份`,
      sourcePickerDefault: "默认不选择任何资料",
      sourcePickerAria: "可供智能体使用的项目资料",
      sourcePickerEmpty: "当前项目暂无可选资料。请先到“资料”页导入。",
      sourcePickerSafety: "只发送你逐项勾选且抽取成功的资料；中文与英文资料不会自动混合或翻译。",
      manifestTitle: "本次输入",
      manifestDescription: "发送前请核对：网页端会要求后端重建或包含以下内容。",
      manifestTargetScene: "目标场景",
      manifestOutputLanguage: "输出语言",
      manifestSavedDraft: "已保存草稿",
      manifestLocalDraftState: "本地草稿状态",
      manifestContextPack: "上下文包",
      manifestPolicy: "资料语言策略",
      manifestWebSearch: "联网状态",
      manifestSources: "已选资料",
      manifestExcluded: "不包含",
      manifestNoSavedDraft: "没有已保存草稿",
      manifestDraftDirty: "本地编辑与已保存草稿不同——已阻止发送",
      manifestDraftScopeMismatch: "已保存草稿属于另一个项目或场景——已阻止发送",
      manifestDraftSynced: "与精确的已保存草稿一致",
      manifestContextRebuilt: "发送时重建，不复用当前预览",
      manifestWebQuery: (query: string) => `已启用 · 查询：${query}`,
      manifestWebEnabled: "已启用 · 将使用本次指令作为查询",
      manifestWebDisabled: "未启用",
      manifestSourceBlocked: "被当前策略阻止",
      sourceMissing: "已选资料当前不可用",
      sourceMissingHelp: "当前列表已找不到这个稳定资料 ID；发送前请取消勾选。"
    },
    settings: {
      desktopBackend: "桌面后端",
      apiAddress: "接口地址",
      configuredWorkspace: "配置工作区",
      backendStatus: "运行状态",
      healthWorkspace: "健康检查工作区",
      process: "进程",
      notReturned: "未返回",
      notConnected: "未连接",
      externalOrUnknownProcess: "外部或未知进程",
      notRunning: "未运行",
      managedProcess: "受管",
      externalProcess: "外部",
      externalBackendWarning: "当前连接的是外部后端；退出桌面壳不会停止这个进程。",
      refreshBackend: "刷新后端",
      startOrConnect: "启动/连接",
      stopManagedBackend: "停止受管后端",
      modelSection: "核心模型",
      writerMode: "写作模式",
      ruleBasedMode: "本地规则模式",
      llmMode: "兼容接口的大模型",
      providerName: "供应商名称",
      baseUrl: "基础网址",
      model: "模型",
      requestJsonMode: "请求结构化响应",
      apiKeySection: "模型密钥",
      currentKey: "当前密钥",
      configuredKey: "已配置",
      hiddenKey: "隐藏",
      replaceKey: "替换密钥",
      keyPlaceholder: "留空表示保留现有密钥",
      clearKey: "清除已保存密钥",
      permissionSection: "权限级别",
      permissionWarning: "保存后权限立即生效；具体正典写入仍需要后端完全权限和人工来源记录。",
      versionSection: "版本与更新",
      currentVersion: "当前版本",
      publishedAt: "发布时间",
      desktopUpdateNote: "桌面版使用签名更新；网页版只提供软件发布页的安装器下载提示。",
      installUpdate: "安装更新并重启",
      downloadInstaller: "下载新版安装器",
      refreshSettings: "刷新",
      checkUpdates: "检查更新",
      saveSettings: "保存设置"
    },
    runtime: {
      updateIdle: "尚未检查更新。",
      updateChecking: "正在检查更新…",
      desktopUpdateAvailable: (version: string) => `发现新版本 ${version}，可在程序内安装并重启。`,
      installerUpdateAvailable: (version: string) => `发现新版本 ${version}，可下载 Windows 安装器。`,
      updateCurrent: (version: string) => `未发现高于当前界面 ${version} 的更新。后端版本请同时核对。`,
      updateDownloading: (version: string) => `正在下载并验证 ${version}；本地后端继续运行。`,
      updateAwaitingEdits: "更新已下载；请先处理尚未保存的正文或提案，再开始安装。",
      updateDownloaded: (version: string) => `${version} 已下载，尚未安装。`,
      updateInstallDestination: "安装更新并重启应用",
      updateExternalUntouched: "没有启动或替换外部后端。",
      updateCancelFailed: "无法解除更新准备状态。请先保留未保存文本，再从托盘退出并重新打开应用。",
      updateChannelUnavailable: "桌面更新通道暂不可用。",
      noGithubRelease: "暂未发布新版安装器，当前版本可继续使用。",
      invalidGithubRelease: "最新发布版本没有有效版本号。",
      updateCheckFailed: "暂时无法检查更新。",
      noInstallableUpdate: "没有可安装的桌面更新，请先检查更新。",
      installingUpdate: (version: string) => `正在准备安装 v${version}，完成后会重启应用。`,
      installedRestarting: "更新已安装，应用正在重启。",
      installedManualRestart: "更新已安装，但自动重启失败。请手动退出并重新打开应用以完成更新。",
      backendRecovered: "本地后端已恢复，工作台可以继续使用。",
      backendRecoveredIncompatible: "本地后端已启动，但工作区不兼容。",
      backendRecoveryFailed: "本地后端恢复失败。请先保留未保存文本，再从托盘退出并重新打开应用。",
      updateDownloadFailed: "更新包下载或验证失败，安装尚未开始。",
      updatePreparationFailed: "无法完成更新准备，安装尚未开始，应用文件未被替换。",
      updateInstallFailed: "安装更新失败。",
      updateFileLockHelp: "程序文件仍被占用。请先保存或备份未保存文本，从托盘退出应用，再打开官方安装包并安装到原目录。",
      backendStopExternal: "已请求停止受管后端；仍检测到外部后端在运行。",
      backendStopped: "受管后端已停止。",
      backendNotConnected: "后端未连接",
      backendWorkspaceConflict: "后端工作区冲突",
      backendManaged: "受管后端",
      backendExternal: "外部后端",
      backendConnectedManaged: "已连接，桌面受管",
      backendConnectedExternal: "已连接，外部进程",
      modelKeyMissing: "大模型未配置密钥",
      localRules: "本地规则",
      apiAddressAria: "接口地址",
      archiveDemo: (nodes: number, relationships: number) =>
        `内置演示已从工作区移除：归档 ${nodes} 个节点、${relationships} 条关系。`,
      draftSaved: (version: number) => `草稿 v${version} 已保存。`,
      draftGenerated: (version: number) => `草稿 v${version} 已生成。`,
      workflowStatus: (status: string) => `工作流状态：${status}。`,
      proposalSaved: (version: number) => `协作草稿已保存为 v${version}；草稿库、候选事实和正典均未改变。`,
      proposalCreated: (version: number) => `协作草稿已创建为 v${version}；尚未进入草稿库、候选事实或正典。`,
      proposalRevised: (version: number) => `智能体已修订协作草稿为 v${version}；当前场景草稿未被覆盖。`,
      factDraftCreated: (count: number) => count
        ? `已生成事实草稿协作提案，包含 ${count} 条候选预览。`
        : "已生成事实草稿协作提案，当前草稿未发现候选事实。",
      proposalSubmitted: (id: string) => `协作草稿 ${id} 已标记为待审。`,
      proposalDecided: (accepted: boolean) => `协作草稿已${accepted ? "接受" : "拒绝"}；正典未改变。`,
      proposalPromoted: (version: number) => `已转为当前场景草稿 v${version}；正典未改变。`,
      structureApplied: (chapters: number, scenes: number, reused: boolean) => reused
        ? `该项目结构已应用过：复用 ${chapters} 个章节、${scenes} 个场景；正典事实仍未改变。`
        : `已应用项目结构：创建 ${chapters} 个章节、${scenes} 个场景；正典事实仍未改变。`,
      candidatesSubmitted: (count: number) => count
        ? `已提交 ${count} 条候选事实；正典尚未改变。`
        : "来源草稿中没有可抽取的候选事实。",
      factReviewed: (action: string, resumed: boolean) =>
        `候选事实已${action}${resumed ? "，工作流审阅暂停已恢复" : ""}。`,
      characterCreated: (id: string, filled: boolean) =>
        `人物已写入正典初始化：${id}${filled ? "；已填入场景视角和出场人物表单，保存场景元数据后生效" : ""}。`,
      locationCreated: (id: string, filled: boolean) =>
        `地点已写入正典初始化：${id}${filled ? "；已填入场景地点表单，保存场景元数据后生效" : ""}。`
    },
    inspector: {
      noContextTitle: "暂无上下文包",
      noContextText: "构建上下文后可检查正典、预算和缺口。",
      budget: "预算",
      graphQueries: "图查询",
      mustInclude: "必须包含",
      mustNotViolate: "禁止违反",
      relationships: "关系",
      foreshadowing: "伏笔",
      missingContext: "缺失上下文",
      droppedItems: "已丢弃项目",
      currentStep: "当前步骤",
      reviewPayload: "审阅载荷",
      continuity: "连续性",
      blockingIssues: "阻塞问题",
      summary: "摘要",
      checkedDimensions: "检查维度",
      issues: "问题",
      suggestion: "建议",
      noReportTitle: "暂无质检报告",
      noReportText: "运行场景工作流后可查看连续性检查结果。",
      runSteps: "运行步骤",
      noFactsTitle: "暂无待审事实",
      noFactsText: "抽取出的状态变化会在这里等待人工审阅。"
    },
    outlineLanguage: {
      tools: "目录工具", generate: "修复目录语言", apply: "应用目录修复", alreadyApplied: "目录修复已应用",
      auditDetails: "高级：版本与来源记录", historyHelp: "查看已保存的目录修复版本及其来源和应用记录。",
      help: "按小说的内容语言生成修改建议，只发送已保存的章节与场景标题、摘要和规划字段，不发送正文或资料。先检查对照，再审阅、接受并应用。",
      reviewTitle: "目录语言修改对照", reviewHelp: "接受提案后仍需点击“应用目录修复”才会更新目录；正文不会被修改。",
      field: "字段", before: "当前内容", after: "建议内容", advanced: "高级：编辑提案数据",
      invalidPreview: "提案数据格式无效，无法预览或应用。请在高级编辑中修正并保存。",
      generated: (count: number) => `已生成 ${count} 项目录修改建议，请检查并提交审阅。`,
      applied: (count: number, already: boolean) => already ? "这份目录修复已应用，目录和图谱已刷新。" : `已应用 ${count} 项目录修改，正文保持不变。`,
      fields: { title: "标题", summary: "摘要", purpose: "章节用途", goal: "目标", conflict: "冲突", timeline_position: "时间位置", outcome: "结果", emotional_turn: "情绪转折" }
    },
    graph: {
      title: "图谱 / 时间线",
      emptyTitle: "暂无后端图谱预览",
      emptyText: "选择真实项目后，这里会显示正典图谱中的正典节点关系和场景时间线。",
      noRelationships: "暂无可预览关系。",
      truncated: "预览已截断，只显示前几条关系。",
      noScenes: "暂无场景"
    },
    notices: {
      sourceImportNoSelection: "没有选择要导入的文件。",
      sourceImportFinished: "资料导入已结束；详细结果保留在资料页。",
      sourceRetryFinished: "资料重试已结束；结果已刷新。",
      sourceSavedAsDraft: (title: string, version: number) => `“${title}”已显式保存为当前场景草稿 v${version}。`,
      sourceSavedAsStyle: (title: string) => `“${title}”已显式保存为风格样本。`,
      sourceSavedAsProposal: (title: string) => `“${title}”已显式保存到协作草稿箱。`,
      sourceStructureCreated: (chapters: number, scenes: number, truncated: boolean) =>
        `已从项目资料生成 ${chapters} 章、${scenes} 个场景的结构草稿${truncated ? "（输入已截断）" : ""}；尚未写入项目树。`,
      sourceArchived: (title: string) => `“${title}”已归档；已有稳定来源引用仍保留。`,
      sourceAddedToAgent: (title: string) => `已为本次智能体请求选中“${title}”；没有复制正文，也没有生成任何内容。`,
      sourceAddedToAgentBlocked: (title: string) => `已选中“${title}”并打开智能体；它会继续显示，但在你主动更改语言策略前无法发送。`,
      proposalCreatedNotOpened: (id: string) => `已创建提案 ${id}，但当前未保存的提案编辑仍原样保留，没有被新结果替换。`,
      savedDraftRestored: (id: string, version: number) => `已恢复精确的已保存草稿 ${id} / v${version}。`,
      promotedDraftOpened: (id: string, version: number) => `已在写作中打开精确草稿 ${id} / v${version}，没有再次提升。`,
      agentSourceLimit: "一次最多选择 32 份项目资料。",
      settingsSaved: "智能体设置已保存。",
      projectCreated: "项目已创建。可以先导入已有小说，并生成章节/场景结构草稿。",
      projectUpdated: "项目信息已更新。",
      chapterUpdated: "章节元数据已更新。",
      chapterCreated: "章节已写入正典初始化。",
      sceneCreated: "场景已创建，可保存草稿或运行智能体工作流。",
      sceneUpdated: "场景元数据已更新；可以重新构建上下文包。",
      worldRuleCreated: "世界规则已写入正典初始化。",
      contextRefreshed: "上下文包已刷新。",
      openedFactReview: "已打开候选事实审阅队列。",
      agentSceneDraftCreated: "智能体已生成场景草稿协作提案；当前场景草稿未被覆盖。",
      agentDiscussionCreated: "智能体已生成讨论记录；请在协作草稿箱中审阅。",
      draftSelectionRequired: "请先在场景草稿中选中一段文字。",
      updateInstalledRestarting: "更新已安装，应用正在重启。"
    },
    errors: {
      outlineLanguagePermission: "当前权限不允许执行此目录操作，请在设置中检查权限。",
      outlineLanguageNoChanges: "当前目录没有需要修改的语言内容。",
      outlineLanguageStale: "目录或项目语言已变化，旧提案不能直接应用。请重新生成目录修复提案。",
      outlineLanguageInvalid: "目录修复提案格式或修改范围无效，请检查提案数据。",
      outlineLanguageUnsupported: "当前后端不支持安全应用目录修复，请先升级后端。",
      outlineLanguageScopeChanged: "当前项目或后端连接已变化，请在目标项目中重新执行。",
      outlineLanguageProviderEndpoint: "当前服务商找不到配置的模型或接口。请检查 API 地址，在设置中刷新可用模型，选择服务商实际提供的模型并保存。",
      outlineLanguageProviderCredentials: "服务商拒绝了认证。请检查已保存的 API 密钥及该密钥的模型访问权限。",
      outlineLanguageProviderRateLimit: "服务商的请求速率或额度受限。请检查服务额度，或稍后再试。",
      outlineLanguageProviderInvalidRequest: "服务商不接受这次请求。请核对所选模型及其接口兼容性。",
      outlineLanguageProviderUnavailable: "服务商暂时不可用，请稍后再试。",
      outlineLanguageProviderConnection: "无法连接配置的服务商。请检查 API 地址和网络连接。",
      outlineLanguageProviderResponse: "服务商响应格式不符合预期。请检查所选模型及其接口兼容性。",
      outlineLanguageProviderFailed: "服务商未能完成目录修复。请检查模型配置和服务状态后再试。",
      selectProjectOrCreate: "请先选择或创建项目。",
      selectProject: "请先选择项目。",
      projectNameRequired: "请先填写小说项目名称。",
      projectNameNotEmpty: "项目名称不能为空。",
      projectLanguageRequired: "请选择中文或英文作为小说内容语言。",
      chooseChapterForEdit: "请先选择要整理的章节。",
      chapterTitleRequired: "请填写章节标题。",
      chooseChapter: "请先选择章节。",
      sceneTitleRequired: "请填写场景标题。",
      chooseSceneForEdit: "请先选择要整理的场景。",
      characterNameRequired: "请填写人物名称。",
      locationNameRequired: "请填写地点名称。",
      worldRuleRequired: "请填写规则领域和规则内容。",
      selectScene: "请先选择场景。",
      agentInstructionRequired: "请先写下想和智能体讨论的问题。",
      agentSelectionRequired: "请先填入或从草稿选中需要修改的片段。",
      agentRevisionRequiresSavedDraft: "请先保存当前草稿，再让智能体修改场景或选中片段。",
      agentIncludedDraftMustBeSaved: "本次请求包含当前草稿，但本地编辑与已保存草稿并不完全一致。请先保存，或恢复已保存版本后再发送。",
      agentDraftScopeMismatch: "当前显示的已保存草稿不属于所选项目与场景。请返回写作区，等待该场景草稿载入后再发送。",
      agentSourcesBlockedByPolicy: "一份或多份已选资料当前不可用，或被语言策略阻止。请移除它们，或主动更改策略后再发送。",
      selectProjectAndScene: "请先创建并选择一个项目和场景。",
      selectSceneForDraft: "请先创建并选择一个场景。",
      selectProjectForStyle: "请先创建并选择项目。",
      sourceNotReadyStructure: "只有文本抽取成功的项目资料才能生成结构草稿。",
      sourceDetailNotReady: "资料全文尚未成功加载，或文本抽取未成功。",
      sourceEmptyText: "文件中没有可用文本。",
      sourceUnsafePath: "文件相对路径不安全，已停止导入。",
      sourceUnsupportedFormat: "当前仅支持 TXT、Markdown 和 DOCX，此文件未导入。",
      sourceRetryFormatMismatch: "重试文件格式与原资料不一致，请重新选择同格式文件。",
      webCryptoUnavailable: "当前运行环境不支持文件指纹校验，无法安全导入。",
      docxExtractionFailed: (detail: string) => `DOCX 文本抽取失败：${detail}`,
      documentNotReadyDraft: "这个文档还不能保存为草稿。",
      documentNotReadyStyle: "这个文档还不能保存为风格样本。",
      documentNotReadyStructure: "这个文档还不能生成结构草稿。",
      documentNotReadyFacts: "这个文档还不能抽取设定。",
      documentNotReadyProposal: "这个文档还不能保存为协作草稿。",
      selectProposal: "请先选择协作草稿。",
      selectProjectStructureProposal: "请先选择项目结构草稿。",
      selectSceneAndProposal: "请先选择场景和协作草稿。",
      proposalActionUnavailable: "当前状态不能执行这项提案操作，或需要先处理未保存修改。",
      proposalTargetMismatch: "当前场景不是这份提案精确记录的目标，已阻止提升。",
      proposalTargetAmbiguous: "这份提案没有唯一且无歧义的场景目标，已阻止提升。",
      proposalTargetMissing: "当前没有选中可用于这份提案目标的场景，已阻止提升。",
      proposalDerivedDraftAmbiguous: "记录了多个衍生草稿引用，已阻止提升。",
      proposalAlreadyPromoted: "这份提案已经记录了精确的已提升草稿。",
      sourceDraftRequired: "请提供真实来源草稿编号。",
      workflowMissingDraft: "工作流未返回草稿库草稿。",
      noInstallableDesktopUpdate: "没有可安装的桌面更新，请先检查更新。"
      ,requestFailed: "操作未完成。请展开技术详情后重试。",
      generatedLanguageConflict: "生成的标题或摘要与项目语言不符。请重试，或编辑提案后再应用。",
      technicalDetails: "技术详情",
      sourceLanguageRequired: "请先把资料语言修正为中文或英文。",
      sourceContentLanguageMismatch: "只有与小说内容语言相同的资料才能直接设为草稿、协作草稿或风格样本。异语资料只能在显式参考模式下交给智能体分析。",
      mixedLanguageStructure: "项目结构分析默认只使用与小说内容语言相同的资料。异语资料必须显式开启参考模式，且不会自动翻译。"
    }
  },
  demoText: {
    "Fantasy Demo": "奇幻演示",
    fantasy: "奇幻",
    demo: "演示",
    "third-person limited": "第三人称有限视角",
    "The Old Bell Tower": "旧钟塔",
    "The Tower Search": "钟塔搜寻",
    "Lin Jin": "林瑾",
    "Helian Ya": "赫连雅",
    "Silver Crow Society": "银鸦会",
    "Old Bell Tower": "旧钟塔",
    "Half Black Wax Seal": "半枚黑蜡封",
    protagonist: "主角",
    "faction agent": "敌对派系探员",
    "secretly protective": "暗中保护林瑾",
    searching: "正在搜寻线索",
    tower: "塔楼",
    clue: "线索",
    missing: "下落不明",
    "controlled by the Silver Crow Society": "被银鸦会控制",
    "Control the tower district.": "控制钟塔街区。",
    "Find the missing sealed letter.": "找到遗失的密封信。",
    "Lin Jin carries royal blood.": "林瑾身负王室血脉。",
    "Do not reveal before scene_005.": "不要在第五场景之前揭示。",
    "The bell rings earlier than expected.": "钟声比预期更早响起。",
    "The underground bell array has been activated.": "地下钟阵已经被启动。",
    seeded: "已埋设",
    high: "高",
    knowledge: "知识边界",
    "Royal lineage secrets require explicit scene-level reveal events.":
      "王室血脉秘密必须通过明确的场景级揭示事件才能进入角色认知。",
    "three days after the capital coup": "王都政变三日后",
    "search for the missing sealed letter": "寻找遗失的密封信",
    "the tower is controlled by a hostile faction": "钟塔被敌对派系控制",
    "Lin Jin finds a physical clue but not the lineage truth.":
      "林瑾找到实体线索，但尚未得知血脉真相。",
    "suspicion sharpens into wary resolve": "怀疑转为克制而警觉的决心",
    "bell rings early": "钟声提前响起",
    "half black wax seal": "半枚黑蜡封",
    "Lin Jin learns secret_lineage": "林瑾得知王室血脉秘密",
    "cold and restrained": "冷峻克制",
    "short lines with subtext": "短句与潜台词",
    "omniscient explanation": "全知解释",
    "uneasy acquaintance": "互不信任的熟人",
    character_linj: "林瑾",
    character_helianya: "赫连雅",
    location_old_bell_tower: "旧钟塔",
    project_fantasy_demo: "奇幻演示",
    chapter_001: "旧钟塔",
    scene_003: "钟塔搜寻",
    item_black_seal_half: "半枚黑蜡封",
    secret_lineage: "王室血脉秘密",
    foreshadowing_early_bell: "提前响起的钟声",
    worldrule_secret_reveals: "秘密揭示规则",
    organization_silver_crow: "银鸦会",
    "character_linj distrusts character_helianya": "林瑾不信任赫连雅",
    HAS_CHAPTER: "包含章节",
    HAS_SCENE: "包含场景",
    KNOWS: "认识",
    KNOWS_SECRET: "知道秘密",
    LOCATED_AT: "位于",
    CONTAINS_ITEM: "包含物件",
    POINTS_TO: "指向",
    BELIEVES_FALSELY: "错误相信",
    SUSPECTS: "怀疑",
    HIDES_FROM: "隐瞒",
    ItemState: "物件状态",
    CharacterState: "角色状态",
    RelationshipState: "关系状态",
    WorldRuleState: "世界规则状态"
  },
  graphLabels: {
    Project: "项目", Character: "人物", Organization: "组织", Location: "地点",
    Item: "物件", Event: "事件", Scene: "场景", Chapter: "章节",
    Secret: "秘密", Foreshadowing: "伏笔", WorldRule: "世界规则", StyleProfile: "文风设定",
    KNOWS: "认识", LOVES: "爱慕", HATES: "憎恨", LOYAL_TO: "忠于",
    BETRAYED: "背叛了", FAMILY_OF: "亲属关系", MENTOR_OF: "指导",
    RIVAL_OF: "竞争对手", KNOWS_SECRET: "知道秘密", BELIEVES_FALSELY: "错误相信",
    SUSPECTS: "怀疑", HIDES_FROM: "隐瞒", LOCATED_AT: "位于", CONTROLS: "控制",
    OWNED_BY: "归属于", PART_OF: "属于", CAUSES: "导致", CONSEQUENCE_OF: "源于",
    PARTICIPATED_IN: "参与", OCCURRED_AT: "发生于", OCCURRED_IN_SCENE: "发生在场景",
    SEEDED_IN: "埋设于", POINTS_TO: "指向", PAID_OFF_IN: "回收于",
    HAS_CHAPTER: "包含章节", HAS_SCENE: "包含场景", NEXT_SCENE: "下一场景",
    CONTAINS_ITEM: "包含物件"
  },
  statuses: {
    idle: "空闲",
    ready: "可用",
    pending: "等待中",
    planned: "已规划",
    drafting: "起草中",
    archived: "已归档",
    running: "运行中",
    completed: "已完成",
    pass: "通过",
    awaiting_review: "等待审阅",
    needs_revision: "需要修订",
    blocked: "已阻塞",
    failed: "失败",
    skipped: "已跳过",
    inconclusive: "未定",
    accepted: "已接受",
    rejected: "已拒绝",
    deferred: "已延后",
    edited: "已编辑",
    none: "无",
    "not checked": "未检查"
  },
  severities: {
    critical: "严重",
    high: "高",
    medium: "中",
    low: "低"
  },
  dimensions: {
    knowledge_boundary: "人物知识边界",
    timeline: "时间线",
    location_state: "地点状态",
    relationship_state: "关系状态",
    world_rule: "世界规则",
    foreshadowing: "伏笔",
    causality: "因果",
    pov: "叙述视角",
    style_constraint: "文风约束"
  },
  issueTypes: {
    knowledge_boundary_violation: "人物知识边界违规",
    timeline_conflict: "时间线冲突",
    location_conflict: "地点冲突",
    relationship_conflict: "关系冲突",
    world_rule_conflict: "世界规则冲突",
    missing_required_element: "缺少必要元素",
    unsupported_new_fact: "未支持的新事实",
    style_drift: "文风漂移",
    foreshadowing_mismatch: "伏笔不匹配",
    causal_gap: "因果缺口",
    pov_leak: "视角泄露"
  },
  steps: {
    build_context: "构建上下文",
    write_draft: "写作草稿",
    check_continuity: "连续性检查",
    extract_state: "抽取状态",
    human_review: "人工审阅"
  },
  proposalTypes: {
    scene_draft: "场景草稿",
    fact_draft: "事实草稿",
    scene_rebuild: "场景重建",
    canon_patch: "正典补丁",
    outline_draft: "大纲草稿",
    project_structure_draft: "项目结构草稿"
  },
  proposalStatuses: {
    drafting: "起草中",
    agent_revised: "智能体已修订",
    author_revised: "作者已修订",
    ready_for_review: "待审",
    accepted: "已接受",
    rejected: "已拒绝"
  },
  permissions: {
    labels: {
      read_only: "仅读取",
      read_generate: "可读取生成",
      full: "完全权限"
    },
    descriptions: {
      read_only: "只能读取正典、草稿、协作草稿、上下文包、运行记录和待审事实。",
      read_generate: "可读取并生成草稿、协作草稿、检查结果、候选事实和风格样本。",
      full: "允许完整本地作者操作，包括人工初始化、协作草稿决策和候选事实审阅决策。"
    }
  },
  reviewActions: {
    accept: "接受",
    reject: "拒绝",
    defer: "延后"
  },
  refKinds: {
    scene_draft_baseline: "生成首稿时的正文状态",
    project: "项目",
    canon_event: "正典变更记录",
    author_instruction: "作者指令",
    imported_document: "导入文档",
    source_document: "项目资料",
    draft: "草稿",
    scene: "场景",
    chapter: "章节",
    graph_node: "图谱节点",
    graph_relation: "图谱关系",
    candidate_fact: "候选事实",
    context_pack: "上下文包",
    continuity_report: "连续性报告",
    workflow_run: "工作流运行",
    style_sample: "风格样本",
    proposal_artifact: "协作提案"
  },
  provenanceMethods: {
    manual: "手动创建",
    llm: "大模型生成",
    import: "导入生成",
    workflow: "工作流生成",
    api: "接口创建"
  },
  knownMessages: {
    "Human review completed.": "人工审阅已完成。"
  }
} as const;
