export const zhCN = {
  demoText: {
    "Fantasy Demo": "奇幻演示",
    fantasy: "奇幻",
    demo: "演示",
    "third-person limited": "第三人称有限视角",
    "The Old Bell Tower": "旧钟塔",
    "The Tower Search": "钟塔搜寻",
    "Lin Jin": "林瑾",
    "Helian Ya": "赫连雅",
    "Silver Crow Society": "银鸦会",
    "Old Bell Tower": "旧钟塔",
    "Half Black Wax Seal": "半枚黑蜡封",
    protagonist: "主角",
    "faction agent": "敌对派系探员",
    "secretly protective": "暗中保护林瑾",
    searching: "正在搜寻线索",
    tower: "塔楼",
    clue: "线索",
    missing: "下落不明",
    "controlled by the Silver Crow Society": "被银鸦会控制",
    "Control the tower district.": "控制钟塔街区。",
    "Find the missing sealed letter.": "找到遗失的密封信。",
    "Lin Jin carries royal blood.": "林瑾身负王室血脉。",
    "Do not reveal before scene_005.": "不要在 scene_005 之前揭示。",
    "The bell rings earlier than expected.": "钟声比预期更早响起。",
    "The underground bell array has been activated.": "地下钟阵已经被启动。",
    seeded: "已埋设",
    high: "高",
    knowledge: "知识边界",
    "Royal lineage secrets require explicit scene-level reveal events.":
      "王室血脉秘密必须通过明确的场景级揭示事件才能进入角色认知。",
    "three days after the capital coup": "王都政变三日后",
    "search for the missing sealed letter": "寻找遗失的密封信",
    "the tower is controlled by a hostile faction": "钟塔被敌对派系控制",
    "Lin Jin finds a physical clue but not the lineage truth.":
      "林瑾找到实体线索，但尚未得知血脉真相。",
    "suspicion sharpens into wary resolve": "怀疑转为克制而警觉的决心",
    "bell rings early": "钟声提前响起",
    "half black wax seal": "半枚黑蜡封",
    "Lin Jin learns secret_lineage": "林瑾得知 secret_lineage",
    "cold and restrained": "冷峻克制",
    "short lines with subtext": "短句与潜台词",
    "omniscient explanation": "全知解释",
    "uneasy acquaintance": "互不信任的熟人",
    character_linj: "林瑾",
    character_helianya: "赫连雅",
    location_old_bell_tower: "旧钟塔",
    project_fantasy_demo: "奇幻演示",
    chapter_001: "旧钟塔",
    scene_003: "钟塔搜寻",
    item_black_seal_half: "半枚黑蜡封",
    secret_lineage: "王室血脉秘密",
    foreshadowing_early_bell: "提前响起的钟声",
    worldrule_secret_reveals: "秘密揭示规则",
    organization_silver_crow: "银鸦会",
    "character_linj distrusts character_helianya": "林瑾不信任赫连雅",
    HAS_CHAPTER: "包含章节",
    HAS_SCENE: "包含场景",
    KNOWS: "认识",
    KNOWS_SECRET: "知道秘密",
    LOCATED_AT: "位于",
    CONTAINS_ITEM: "包含物件",
    POINTS_TO: "指向",
    BELIEVES_FALSELY: "错误相信",
    SUSPECTS: "怀疑",
    HIDES_FROM: "隐瞒",
    ItemState: "物件状态",
    CharacterState: "角色状态",
    RelationshipState: "关系状态",
    WorldRuleState: "世界规则状态"
  },
  statuses: {
    planned: "已规划"
  }
} as const;
