export const zhCN = {
  locale: "zh-CN",
  app: {
    documentTitle: "StoryGraph 写作台",
    brandName: "StoryGraph Agent",
    tagline: "长篇小说安全写作台"
  },
  terms: {
    agent: "智能体（Agent）",
    api: "API",
    candidateFact: "候选事实（CandidateFact）",
    canon: "正典（canon）",
    canonReview: "正典审阅",
    canonSeed: "正典初始化（canon seed）",
    contextPack: "上下文包（Context Pack）",
    draftStore: "草稿库（Draft Store）",
    factDraft: "事实草稿（fact_draft）",
    fastApi: "FastAPI 后端",
    graphStore: "正典图谱（Graph Store）",
    githubRelease: "GitHub Release（发布版本）",
    llm: "大模型（LLM）",
    proposalStore: "协作提案库（Proposal Store）",
    reviewService: "审阅服务（ReviewService）",
    styleSampleStore: "风格样本库（StyleSample Store）",
    tauri: "Tauri 桌面版"
  },
  ui: {
    common: {
      all: "全部",
      cancel: "取消",
      checking: "正在检查...",
      create: "创建",
      missing: "缺失",
      none: "无",
      loading: "读取中",
      newItem: "新建",
      notConfigured: "未配置",
      refresh: "刷新",
      save: "保存"
    },
    commandBar: {
      ariaLabel: "全局命令",
      saveDraftTitle: "保存当前场景草稿",
      undoTitle: "撤销当前输入框编辑",
      redoTitle: "重做当前输入框编辑",
      refreshTitle: "刷新后端项目树",
      sourcesTitle: "打开本地资料与大模型设定抽取",
      agentTitle: "打开智能体对话",
      proposalsTitle: "打开协作草稿箱",
      runTitle: "根据当前正典和上下文运行场景写作工作流"
    },
    tabs: {
      write: "写作",
      sources: "资料",
      agent: "智能体对话",
      proposals: "协作草稿",
      workflow: "工作流",
      context: "上下文",
      continuity: "质检",
      facts: "事实",
      settings: "设置"
    },
    stateStrip: {
      projectPrefix: "项目",
      writerPrefix: "写作器",
      llmIncomplete: "大模型设置未完整",
      safetyBoundary: "草稿、候选事实、正典分离"
    },
    workspace: {
      emptyTitle: "当前后端没有真实项目",
      emptyText: "请先创建自己的小说项目；创建后可导入已有小说，让智能体生成章节和场景结构草稿。",
      importedStructureTitle: "导入小说生成项目结构",
      emptyWorkspaceTitle: "空工作区",
      noSceneWithWorkspace: "先在“资料”中导入已有小说，由智能体生成章节/场景结构草稿；作者确认后再写入正式项目树。",
      noSceneEmptyWorkspace: "先创建项目，再导入已有小说生成章节/场景结构草稿。",
      sceneMetadataAria: "场景元数据",
      mainWorkspaceAria: "主工作区",
      workflowStatusAria: "当前工作流状态"
    },
    library: {
      title: "本地资料 / 导入",
      summary: "个本地文档 / 默认只在浏览器内存 / 非正典",
      fileButton: "文件",
      folderButton: "文件夹",
      clearButton: "清空",
      emptyTitle: "还没有导入文档",
      emptyText: "使用“文件”或“文件夹”把 txt、md、docx 加载到本地阅读器。",
      readerEmptyTitle: "选择一个文档",
      readerEmptyText: "导入内容默认只保存在浏览器内存中，不会自动进入草稿、候选事实或正典。",
      bridgeText: "当前是本地阅读器资料；只有点击下面按钮才会写入后端协作提案、草稿、风格样本或候选事实。",
      buildStructure: "生成项目结构草稿",
      buildStructureTitle: "从导入小说生成可编辑的项目结构草稿；作者确认后才会创建章节/场景。",
      saveDraft: "设为当前草稿",
      saveDraftTitle: "保存为当前场景草稿库草稿，不写正典。",
      saveProposal: "存入草稿箱",
      saveProposalTitle: "保存为协作提案库草稿，不写当前场景草稿。",
      saveStyle: "存为风格样本",
      saveStyleTitle: "保存为风格样本库样本，只作为 P6 软参考。",
      llmFactDraft: "大模型抽设定草稿",
      llmFactDraftTitle: "把导入资料发送给已配置的大模型，生成可编辑事实草稿；不会自动进入正典。",
      parseMarkers: "解析显式标记",
      parseMarkersTitle: "保存为草稿后，仅解析文中已有的 [[fact:...]] 显式标记。",
      readErrorTitle: "无法读取这个文档。",
      localRoot: "本地资料",
      emptyDocumentText: "这个文档中没有可读取文本。"
    },
    proposals: {
      ariaLabel: "协作草稿箱",
      title: "协作草稿箱",
      countSuffix: "条 / 协作提案库",
      filterAria: "协作草稿状态筛选",
      emptyTitle: "暂无协作草稿",
      emptyText: "可从本地资料、智能体工作流或手动编辑创建。",
      typeAria: "协作草稿类型",
      titleAria: "协作草稿标题",
      titlePlaceholder: "标题",
      bodyAria: "协作草稿正文",
      save: "保存草稿",
      requestAgent: "请求智能体修改",
      extractFactDraft: "生成事实草稿",
      submitReview: "提交审阅",
      accept: "接受",
      reject: "拒绝",
      promoteDraft: "转为当前场景草稿",
      applyStructure: "应用为章节/场景",
      sourceDraft: "来源草稿",
      sourceDraftPlaceholder: "来源 Draft ID（草稿编号）",
      extractCandidates: "提交为候选事实",
      openCanonReview: "打开正典审阅",
      refsSource: "来源",
      refsTarget: "影响范围",
      refsDerived: "派生",
      metadataStatus: "状态",
      metadataType: "类型",
      metadataVersion: "版本",
      metadataCreatedVia: "创建方式",
      unselected: "未选择",
      newVersion: "新建"
    },
    sidebar: {
      workspaceTitle: "真实工作区",
      projectTreeAria: "后端项目树",
      projectEmpty: "后端还没有项目。",
      projectLoading: "正在读取后端项目...",
      uncategorized: "未分类",
      languageUnset: "未设置语言",
      povUnset: "未设置视角",
      chapterCount: "章",
      sceneCount: "场景",
      refreshTitle: "从后端刷新项目树",
      createProject: "新建项目",
      createProjectTitle: "创建新的小说项目",
      editProject: "编辑项目",
      editProjectTitle: "编辑当前项目信息",
      archiveDemo: "移除演示",
      archiveDemoTitle: "仅移除内置演示项目，真实项目不受影响",
      requireFullPermission: "需要完全权限",
      noChapterScenes: "本章节还没有场景。",
      noProjectTreeTitle: "没有后端项目树",
      noProjectTreeText: "创建项目后，章节和场景会从正典图谱读取。",
      editProjectTitleText: "编辑项目信息",
      createProjectTitleText: "创建新的小说项目",
      projectNamePlaceholder: "项目名称",
      genrePlaceholder: "类型",
      languagePlaceholder: "语言",
      targetLengthPlaceholder: "目标篇幅",
      narrativePovPlaceholder: "叙述视角",
      saveProjectInfo: "保存信息",
      createProjectButton: "创建项目",
      outlineTitle: "章节 / 场景",
      chapterTitlePlaceholder: "章节标题",
      volumeIndexPlaceholder: "卷序号",
      chapterIndexPlaceholder: "章节序号",
      chapterStatusAria: "章节状态",
      addChapter: "添加章节",
      chapterPurposePlaceholder: "章节目的",
      chapterSummaryPlaceholder: "章节摘要",
      loadChapter: "载入当前章节",
      loadChapterTitle: "把当前选中的章节载入上方表单",
      saveChapterMetadata: "保存章节元数据",
      saveChapterMetadataTitle: "保存当前选中章节的元数据",
      chooseChapter: "选择章节",
      sceneTitlePlaceholder: "场景标题",
      sceneIndexPlaceholder: "场景序号",
      addScene: "添加场景",
      loadScene: "载入当前场景",
      loadSceneTitle: "把当前选中的场景载入下方表单",
      saveSceneMetadata: "保存场景元数据",
      saveSceneMetadataTitle: "保存当前选中场景的元数据",
      sceneStatusAria: "场景状态",
      previousScenePlaceholder: "前一场景 ID",
      povCharacterPlaceholder: "视角人物 ID",
      locationPlaceholder: "地点 ID",
      timelinePlaceholder: "时间线",
      sceneGoalPlaceholder: "场景目标",
      sceneConflictPlaceholder: "场景冲突",
      sceneOutcomePlaceholder: "场景结果",
      emotionalTurnPlaceholder: "情绪转折",
      stylePovPlaceholder: "风格视角",
      tensePlaceholder: "时态",
      tonePlaceholder: "语气",
      rhythmPlaceholder: "句式节奏",
      dictionPlaceholder: "用词",
      dialogueStylePlaceholder: "对话风格",
      bannedPatternsPlaceholder: "禁用表达：每行一条",
      requiredCharactersPlaceholder: "出场人物 ID：每行一条",
      mustIncludePlaceholder: "必须包含：每行一条",
      mustNotViolatePlaceholder: "禁止违反：每行一条",
      storyBibleTitle: "人物 / 地点 / 规则",
      characterNamePlaceholder: "人物名称",
      characterRolePlaceholder: "人物作用",
      createCharacter: "人物",
      locationNamePlaceholder: "地点名称",
      locationTypePlaceholder: "地点类型",
      createLocation: "地点",
      ruleDomainPlaceholder: "规则领域",
      worldRulePlaceholder: "世界规则",
      createRule: "规则",
      importedPovLabel: "视角提示",
      importedLocationLabel: "地点提示",
      matchedPrefix: "已匹配",
      useExisting: "使用已有",
      useExistingTitle: "只填入当前场景表单，不保存场景元数据",
      fillCharacter: "填入人物",
      fillCharacterTitle: "只填入人物初始化表单，不写入正典",
      fillLocation: "填入地点",
      fillLocationTitle: "只填入地点初始化表单，不写入正典",
      footer: "导入、草稿、候选事实都不会直接改写正典（canon）。"
    },
    editor: {
      contextButton: "上下文",
      saveButton: "保存",
      generateDraftButton: "仅生成草稿",
      generateDraftTitle: "仅执行构建上下文与写作草稿，并保存到草稿库。",
      runWorkflowButton: "运行场景写作工作流",
      runWorkflowTitle: "根据当前场景正典和上下文写场景草稿，再做质检和候选事实抽取。不会读取本地资料区。",
      goal: "目标",
      conflict: "冲突",
      timeline: "时间线",
      location: "地点",
      draftTitle: "场景草稿",
      unsavedDraft: "本地未保存草稿",
      draftBodyAria: "场景草稿正文",
      draftSummaryAria: "草稿摘要",
      markSelectionForAgent: "标注给智能体",
      markSelectionForAgentTitle: "把最近选中的草稿片段带入智能体对话",
      runTitle: "智能体运行",
      runNotStarted: "尚未运行"
    },
    agentDiscussion: {
      ariaLabel: "智能体对话",
      title: "智能体对话",
      description: "围绕当前场景、选中文本、本地资料和可选联网搜索生成非正典协作提案。",
      llmConfigured: "大模型已配置",
      llmNotConfigured: "大模型未配置",
      mode: "模式",
      modes: {
        discuss: "讨论问题",
        revise_selection: "改写选中段落",
        revise_scene: "改写整场草稿"
      },
      useDraftSelection: "使用草稿选区",
      instructionLabel: "想和智能体讨论什么",
      instructionPlaceholder: "例如：这段情绪转折还不够自然，请保留视角限制并改得更克制。",
      selectionLabel: "标注片段",
      selectionPlaceholder: "从草稿中选择一段后点击“使用草稿选区”，也可以手动粘贴。",
      submit: "发送给智能体",
      openProposal: "打开草稿箱",
      includeContextPack: "包含上下文包",
      includeLatestDraft: "包含当前草稿",
      includeLibrarySources: "浏览已导入资料",
      allowWebSearch: "联网搜索",
      webSearchPlaceholder: "搜索关键词；为空则使用问题文本",
      noSceneTitle: "请先选择场景",
      noSceneText: "智能体对话会绑定当前场景，并把结果保存为协作提案库草稿。",
      proposalMetric: "生成提案",
      replacementMetric: "替换状态",
      fullSceneDraft: "已生成完整场景草稿提案",
      discussionOnly: "讨论记录 / 未覆盖草稿",
      truncatedSources: "已截断资料",
      webResults: "搜索结果"
    },
    settings: {
      desktopBackend: "桌面后端",
      apiAddress: "API 地址",
      configuredWorkspace: "配置工作区",
      backendStatus: "运行状态",
      healthWorkspace: "健康检查工作区",
      process: "进程",
      notReturned: "未返回",
      notConnected: "未连接",
      externalOrUnknownProcess: "外部或未知进程",
      notRunning: "未运行",
      managedProcess: "受管",
      externalProcess: "外部",
      externalBackendWarning: "当前连接的是外部后端；退出桌面壳不会停止这个进程。",
      refreshBackend: "刷新后端",
      startOrConnect: "启动/连接",
      stopManagedBackend: "停止受管后端",
      modelSection: "核心模型",
      writerMode: "写作模式",
      ruleBasedMode: "本地规则模式",
      llmMode: "OpenAI 兼容大模型",
      providerName: "供应商名称",
      baseUrl: "基础 URL",
      model: "模型",
      requestJsonMode: "请求 JSON 模式",
      apiKeySection: "API 密钥",
      currentKey: "当前密钥",
      configuredKey: "已配置",
      hiddenKey: "隐藏",
      replaceKey: "替换密钥",
      keyPlaceholder: "留空表示保留现有密钥",
      clearKey: "清除已保存密钥",
      permissionSection: "权限级别",
      permissionWarning: "保存后权限立即生效；具体正典写入仍需要后端完全权限和人工来源记录。",
      versionSection: "版本与更新",
      currentVersion: "当前版本",
      publishedAt: "发布时间",
      desktopUpdateNote: "桌面版使用 Tauri 签名更新；网页版只提供 GitHub Release（发布版本）下载提示。",
      installUpdate: "安装更新并重启",
      downloadInstaller: "下载新版安装器",
      refreshSettings: "刷新",
      checkUpdates: "检查更新",
      saveSettings: "保存设置"
    },
    inspector: {
      noContextTitle: "暂无上下文包",
      noContextText: "构建上下文后可检查正典、预算和缺口。",
      budget: "预算",
      graphQueries: "图查询",
      mustInclude: "必须包含",
      mustNotViolate: "禁止违反",
      relationships: "关系",
      foreshadowing: "伏笔",
      missingContext: "缺失上下文",
      droppedItems: "已丢弃项目",
      currentStep: "当前步骤",
      reviewPayload: "审阅载荷",
      continuity: "连续性",
      blockingIssues: "阻塞问题",
      summary: "摘要",
      checkedDimensions: "检查维度",
      issues: "问题",
      suggestion: "建议",
      noReportTitle: "暂无质检报告",
      noReportText: "运行场景工作流后可查看连续性检查结果。",
      runSteps: "运行步骤",
      noFactsTitle: "暂无待审事实",
      noFactsText: "抽取出的状态变化会在这里等待人工审阅。"
    },
    graph: {
      title: "图谱 / 时间线",
      emptyTitle: "暂无后端图谱预览",
      emptyText: "选择真实项目后，这里会显示正典图谱中的 CANON 节点关系和场景时间线。",
      noRelationships: "暂无可预览关系。",
      truncated: "预览已截断，只显示前几条关系。",
      noScenes: "暂无场景"
    },
    notices: {
      localLibraryCleared: "本地资料已清空，正典未改变。",
      settingsSaved: "智能体设置已保存。",
      projectCreated: "项目已创建。可以先导入已有小说，并生成章节/场景结构草稿。",
      projectUpdated: "项目信息已更新。",
      chapterUpdated: "章节元数据已更新。",
      chapterCreated: "章节已写入正典初始化。",
      sceneCreated: "场景已创建，可保存草稿或运行智能体工作流。",
      sceneUpdated: "场景元数据已更新；可以重新构建上下文包。",
      worldRuleCreated: "世界规则已写入正典初始化。",
      contextRefreshed: "上下文包已刷新。",
      openedFactReview: "已打开候选事实审阅队列。",
      agentSceneDraftCreated: "智能体已生成场景草稿协作提案；当前场景草稿未被覆盖。",
      agentDiscussionCreated: "智能体已生成讨论记录；请在协作草稿箱中审阅。",
      draftSelectionRequired: "请先在场景草稿中选中一段文字。",
      updateInstalledRestarting: "更新已安装，应用正在重启。"
    },
    errors: {
      selectProjectOrCreate: "请先选择或创建项目。",
      selectProject: "请先选择项目。",
      projectNameRequired: "请先填写小说项目名称。",
      projectNameNotEmpty: "项目名称不能为空。",
      chooseChapterForEdit: "请先选择要整理的章节。",
      chapterTitleRequired: "请填写章节标题。",
      chooseChapter: "请先选择章节。",
      sceneTitleRequired: "请填写场景标题。",
      chooseSceneForEdit: "请先选择要整理的场景。",
      characterNameRequired: "请填写人物名称。",
      locationNameRequired: "请填写地点名称。",
      worldRuleRequired: "请填写规则领域和规则内容。",
      selectScene: "请先选择场景。",
      agentInstructionRequired: "请先写下想和智能体讨论的问题。",
      agentSelectionRequired: "请先填入或从草稿选中需要修改的片段。",
      selectProjectAndScene: "请先创建并选择一个项目和场景。",
      selectSceneForDraft: "请先创建并选择一个场景。",
      selectProjectForStyle: "请先创建并选择项目。",
      documentNotReadyDraft: "这个文档还不能保存为草稿。",
      documentNotReadyStyle: "这个文档还不能保存为风格样本。",
      documentNotReadyStructure: "这个文档还不能生成结构草稿。",
      documentNotReadyFacts: "这个文档还不能抽取设定。",
      documentNotReadyProposal: "这个文档还不能保存为协作草稿。",
      selectProposal: "请先选择协作草稿。",
      selectProjectStructureProposal: "请先选择项目结构草稿。",
      selectSceneAndProposal: "请先选择场景和协作草稿。",
      sourceDraftRequired: "请提供真实来源草稿 ID。",
      workflowMissingDraft: "工作流未返回草稿库草稿。",
      noInstallableDesktopUpdate: "没有可安装的桌面更新，请先检查更新。"
    }
  },
  demoText: {
    "Fantasy Demo": "奇幻演示",
    fantasy: "奇幻",
    demo: "演示",
    "third-person limited": "第三人称有限视角",
    "The Old Bell Tower": "旧钟塔",
    "The Tower Search": "钟塔搜寻",
    "Lin Jin": "林瑾",
    "Helian Ya": "赫连雅",
    "Silver Crow Society": "银鸦会",
    "Old Bell Tower": "旧钟塔",
    "Half Black Wax Seal": "半枚黑蜡封",
    protagonist: "主角",
    "faction agent": "敌对派系探员",
    "secretly protective": "暗中保护林瑾",
    searching: "正在搜寻线索",
    tower: "塔楼",
    clue: "线索",
    missing: "下落不明",
    "controlled by the Silver Crow Society": "被银鸦会控制",
    "Control the tower district.": "控制钟塔街区。",
    "Find the missing sealed letter.": "找到遗失的密封信。",
    "Lin Jin carries royal blood.": "林瑾身负王室血脉。",
    "Do not reveal before scene_005.": "不要在 scene_005 之前揭示。",
    "The bell rings earlier than expected.": "钟声比预期更早响起。",
    "The underground bell array has been activated.": "地下钟阵已经被启动。",
    seeded: "已埋设",
    high: "高",
    knowledge: "知识边界",
    "Royal lineage secrets require explicit scene-level reveal events.":
      "王室血脉秘密必须通过明确的场景级揭示事件才能进入角色认知。",
    "three days after the capital coup": "王都政变三日后",
    "search for the missing sealed letter": "寻找遗失的密封信",
    "the tower is controlled by a hostile faction": "钟塔被敌对派系控制",
    "Lin Jin finds a physical clue but not the lineage truth.":
      "林瑾找到实体线索，但尚未得知血脉真相。",
    "suspicion sharpens into wary resolve": "怀疑转为克制而警觉的决心",
    "bell rings early": "钟声提前响起",
    "half black wax seal": "半枚黑蜡封",
    "Lin Jin learns secret_lineage": "林瑾得知 secret_lineage",
    "cold and restrained": "冷峻克制",
    "short lines with subtext": "短句与潜台词",
    "omniscient explanation": "全知解释",
    "uneasy acquaintance": "互不信任的熟人",
    character_linj: "林瑾",
    character_helianya: "赫连雅",
    location_old_bell_tower: "旧钟塔",
    project_fantasy_demo: "奇幻演示",
    chapter_001: "旧钟塔",
    scene_003: "钟塔搜寻",
    item_black_seal_half: "半枚黑蜡封",
    secret_lineage: "王室血脉秘密",
    foreshadowing_early_bell: "提前响起的钟声",
    worldrule_secret_reveals: "秘密揭示规则",
    organization_silver_crow: "银鸦会",
    "character_linj distrusts character_helianya": "林瑾不信任赫连雅",
    HAS_CHAPTER: "包含章节",
    HAS_SCENE: "包含场景",
    KNOWS: "认识",
    KNOWS_SECRET: "知道秘密",
    LOCATED_AT: "位于",
    CONTAINS_ITEM: "包含物件",
    POINTS_TO: "指向",
    BELIEVES_FALSELY: "错误相信",
    SUSPECTS: "怀疑",
    HIDES_FROM: "隐瞒",
    ItemState: "物件状态",
    CharacterState: "角色状态",
    RelationshipState: "关系状态",
    WorldRuleState: "世界规则状态"
  },
  statuses: {
    idle: "空闲",
    pending: "等待中",
    planned: "已规划",
    drafting: "起草中",
    archived: "已归档",
    running: "运行中",
    completed: "已完成",
    pass: "通过",
    awaiting_review: "等待审阅",
    needs_revision: "需要修订",
    blocked: "已阻塞",
    failed: "失败",
    skipped: "已跳过",
    inconclusive: "未定",
    accepted: "已接受",
    rejected: "已拒绝",
    deferred: "已延后",
    edited: "已编辑",
    none: "无",
    "not checked": "未检查"
  },
  severities: {
    critical: "严重",
    high: "高",
    medium: "中",
    low: "低"
  },
  dimensions: {
    knowledge_boundary: "人物知识边界",
    timeline: "时间线",
    location_state: "地点状态",
    relationship_state: "关系状态",
    world_rule: "世界规则",
    foreshadowing: "伏笔",
    causality: "因果",
    pov: "叙述视角",
    style_constraint: "文风约束"
  },
  issueTypes: {
    knowledge_boundary_violation: "人物知识边界违规",
    timeline_conflict: "时间线冲突",
    location_conflict: "地点冲突",
    relationship_conflict: "关系冲突",
    world_rule_conflict: "世界规则冲突",
    missing_required_element: "缺少必要元素",
    unsupported_new_fact: "未支持的新事实",
    style_drift: "文风漂移",
    foreshadowing_mismatch: "伏笔不匹配",
    causal_gap: "因果缺口",
    pov_leak: "视角泄露"
  },
  steps: {
    build_context: "构建上下文",
    write_draft: "写作草稿",
    check_continuity: "连续性检查",
    extract_state: "抽取状态",
    human_review: "人工审阅"
  },
  proposalTypes: {
    scene_draft: "场景草稿",
    fact_draft: "事实草稿",
    scene_rebuild: "场景重建",
    canon_patch: "正典补丁",
    outline_draft: "大纲草稿",
    project_structure_draft: "项目结构草稿"
  },
  proposalStatuses: {
    drafting: "起草中",
    agent_revised: "智能体已修订",
    author_revised: "作者已修订",
    ready_for_review: "待审",
    accepted: "已接受",
    rejected: "已拒绝"
  },
  permissions: {
    labels: {
      read_only: "仅读取",
      read_generate: "可读取生成",
      full: "完全权限"
    },
    descriptions: {
      read_only: "只能读取正典、草稿、协作草稿、上下文包、运行记录和待审事实。",
      read_generate: "可读取并生成草稿、协作草稿、检查结果、候选事实和风格样本。",
      full: "允许完整本地作者操作，包括人工初始化、协作草稿决策和候选事实审阅决策。"
    }
  },
  reviewActions: {
    accept: "接受",
    reject: "拒绝",
    defer: "延后"
  },
  refKinds: {
    author_instruction: "作者指令",
    imported_document: "导入文档",
    draft: "草稿",
    scene: "场景",
    chapter: "章节",
    graph_node: "图谱节点",
    graph_relation: "图谱关系",
    candidate_fact: "候选事实",
    context_pack: "上下文包",
    continuity_report: "连续性报告",
    workflow_run: "工作流运行",
    style_sample: "风格样本",
    proposal_artifact: "协作提案"
  },
  provenanceMethods: {
    manual: "手动创建",
    llm: "大模型生成",
    import: "导入生成",
    workflow: "工作流生成",
    api: "API 创建"
  },
  knownMessages: {
    "Human review completed.": "人工审阅已完成。"
  }
} as const;
